package com.example.fatin.ipray4mum;

import android.content.Intent;
import android.media.MediaPlayer;
import android.os.Bundle;
import android.support.v7.app.AppCompatActivity;
import android.view.Menu;
import android.view.MenuItem;
import android.widget.ListView;

import java.util.ArrayList;

/**
 * Created by Fatin on 16/01/2018.
 */

public class SurahTaubahMalay extends AppCompatActivity {
    ArrayList<VerseActivity> arrayList;
    private QuranActivity adapter;
    private ListView verseList;

    @Override
    protected void onCreate(Bundle savedInstanceState){
        super.onCreate(savedInstanceState);
        setContentView(R.layout.quranview);

        verseList = (ListView) findViewById(R.id.verseList);
        arrayList = new ArrayList<>();

        /*ayat 1-10*/
        arrayList.add(new VerseActivity("Taubah", "﻿بَرَآءَةٌ مِّنَ ٱللَّهِ وَرَسُولِهِۦٓ إِلَى ٱلَّذِينَ عَٰهَدتُّم مِّنَ ٱلْمُشْرِكِينَ", "(Ini adalah) pemutusan tanggungjawab (pembatalan perjanjian) dari Allah dan RasulNya terhadap kaum kafir musyrik yang kamu mengikat perjanjian setia (dengan mereka).", R.raw.taubah1));
        arrayList.add(new VerseActivity("Taubah", "فَسِيحُوا۟ فِى ٱلْأَرْضِ أَرْبَعَةَ أَشْهُرٍ وَٱعْلَمُوٓا۟ أَنَّكُمْ غَيْرُ مُعْجِزِى ٱللَّـهِ وَأَنَّ ٱللَّـهَ مُخْزِى ٱلْكَـفِرِينَ", "Oleh itu hendaklah kamu (hai kaum musyrik) bergerak di muka bumi (dengan bebasnya) selama empat bulan, dan ketahuilah bahawa kamu tidak terlepas dari (azab seksa) Allah. Dan (ingatlah) sesungguhnya Allah akan menghina orang-orang yang kafir (dengan bala bencana di dunia dan azab seksa di akhirat).", R.raw.taubah2));
        arrayList.add(new VerseActivity("Taubah", "وَأَذَنٌ مِّنَ ٱللَّـهِ وَرَسُولِهِۦٓ إِلَى ٱلنَّاسِ يَوْمَ ٱلْحَجِّ ٱلْأَكْبَرِ أَنَّ ٱللَّـهَ بَرِىٓءٌ مِّنَ ٱلْمُشْرِكِينَ وَرَسُولُهُۥ فَإِن تُبْتُمْ فَهُوَ خَيْرٌ لَّكُمْ وَإِن تَوَلَّيْتُمْ فَٱعْلَمُوٓا۟ أَنَّكُمْ غَيْرُ مُعْجِزِى ٱللَّـهِ وَبَشِّرِ ٱلَّذِينَ كَفَرُوا۟ بِعَذَابٍ أَلِيمٍ", "Dan inilah perisytiharan dari Allah dan RasulNya kepada umat manusia, (diisytiharkan) pada Hari Raya Haji yang terbesar, bahawa sesungguhnya Allah dan RasulNya memutuskan tanggungjawab terhadap orang-orang musyrik; oleh itu jika kamu (wahai kaum musyrik) bertaubat (dari kufur) maka yang demikian adalah baik bagi kamu; dan jika kamu berpaling (ingkar), maka ketahuilah sesungguhnya kamu tidak akan dapat melepaskan diri dari (azab seksa) Allah. Dan khabarkanlah (wahai Muhammad) kepada orang-orang kafir (bahawa mereka akan ditimpakan) dengan azab yang tidak terperi sakitnya.", R.raw.taubah3));
        arrayList.add(new VerseActivity("Taubah", "إِلَّا ٱلَّذِينَ عَـهَدتُّم مِّنَ ٱلْمُشْرِكِينَ ثُمَّ لَمْ يَنقُصُوكُمْ شَيْـًٔا وَلَمْ يُظَـهِرُوا۟ عَلَيْكُمْ أَحَدًا فَأَتِمُّوٓا۟ إِلَيْهِمْ عَهْدَهُمْ إِلَى مُدَّتِهِمْ إِنَّ ٱللَّـهَ يُحِبُّ ٱلْمُتَّقِينَ", "Kecuali mereka yang kamu mengikat perjanjian setia (dengannya) dari orang-orang musyrik, kemudian mereka tidak mencabuli perjanjian kamu itu sedikitpun, dan mereka tidak menolong seorangpun yang memusuhi kamu, maka sempurnakanlah kepada mereka perjanjian mereka sehingga (habis) tempohnya. Sesungguhnya Allah mengasihi orang-orang yang bertaqwa.", R.raw.taubah4));
        arrayList.add(new VerseActivity("Taubah", "﻿فَإِذَا ٱنسَلَخَ ٱلْأَشْهُرُ ٱلْحُرُمُ فَٱقْتُلُوا۟ ٱلْمُشْرِكِينَ حَيْثُ وَجَدتُّمُوهُمْ وَخُذُوهُمْ وَٱحْصُرُوهُمْ وَٱقْعُدُوا۟ لَهُمْ كُلَّ مَرْصَدٍ فَإِن تَابُوا۟ وَأَقَامُوا۟ ٱلصَّلَوةَ وَءَاتَوُا۟ ٱلزَّكَوةَ فَخَلُّوا۟ سَبِيلَهُمْ إِنَّ ٱللَّـهَ غَفُورٌ رَّحِيمٌ", "Kemudian apabila habislah (masa) bulan-bulan yang dihormati itu maka bunuhlah orang-orang musyrik itu di mana sahaja kamu menemuinya, dan tawanlah mereka, dan juga keponglah mereka, serta tunggulah mereka di tiap-tiap tempat mengintipnya. Kemudian jika mereka bertaubat (dari kekufurannya) dan mendirikan sembahyang serta memberi zakat, maka biarkanlah mereka (jangan diganggu). Sesungguhnya Allah Maha Pengampun, lagi Maha Mengasihani.", R.raw.taubah5));
        arrayList.add(new VerseActivity("Taubah", "وَإِنْ أَحَدٌ مِّنَ ٱلْمُشْرِكِينَ ٱسْتَجَارَكَ فَأَجِرْهُ حَتَّى يَسْمَعَ كَلَـمَ ٱللَّـهِ ثُمَّ أَبْلِغْهُ مَأْمَنَهُۥ ذَلِكَ بِأَنَّهُمْ قَوْمٌ لَّا يَعْلَمُونَ", "Dan jika seseorang dari kaum musyrik meminta perlindungan kepadamu (untuk memahami Islam), maka berilah perlindungan kepadanya sehingga ia sempat mendengar keterangan-keterangan Allah (tentang hakikat Islam itu), kemudian hantarlah dia ke mana-mana tempat yang ia beroleh aman. Perintah yang tersebut ialah kerana mereka itu kaum yang tidak mengetahui (hakikat Islam).", R.raw.taubah6));
        arrayList.add(new VerseActivity("Taubah", "﻿كَيْفَ يَكُونُ لِلْمُشْرِكِينَ عَهْدٌ عِندَ ٱللَّـهِ وَعِندَ رَسُولِهِۦٓ إِلَّا ٱلَّذِينَ عَـهَدتُّمْ عِندَ ٱلْمَسْجِدِ ٱلْحَرَامِ فَمَا ٱسْتَقَـمُوا۟ لَكُمْ فَٱسْتَقِيمُوا۟ لَهُمْ إِنَّ ٱللَّـهَ يُحِبُّ ٱلْمُتَّقِينَ", "Bagaimanakah dapat diakui adanya perjanjian (keamanan) di sisi Allah dan RasulNya bagi orang-orang musyrik (sedang mereka mencabulinya)? Kecuali orang-orang (musyrik) yang kamu telah mengikat perjanjian setia dengan mereka dekat Masjid Al-Haraam. Maka selagi mereka berlaku lurus terhadap kamu, hendaklah kamu berlaku lurus pula terhadap mereka; sesungguhnya Allah mengasihi orang-orang yang bertaqwa.", R.raw.taubah7));
        arrayList.add(new VerseActivity("Taubah", "﻿كَيْفَ وَإِن يَظْهَرُوا۟ عَلَيْكُمْ لَا يَرْقُبُوا۟ فِيكُمْ إِلًّا وَلَا ذِمَّةً يُرْضُونَكُم بِأَفْوَهِهِمْ وَتَأْبَى قُلُوبُهُمْ وَأَكْثَرُهُمْ فَـسِقُونَ", "Bagaimana (boleh dikekalkan perjanjian kaum kafir musyrik itu) padahal kalau mereka dapat mengalahkan kamu, mereka tidak akan menghormati perhubungan kerabat terhadap kamu, dan tidak akan menghormati perjanjian setianya. Mereka menjadikan kamu bersenang hati hanya dengan mulut mereka, sedang hati mereka menolaknya; dan kebanyakan mereka adalah orang-orang yang fasik.", R.raw.taubah8));
        arrayList.add(new VerseActivity("Taubah", "ٱشْتَرَوْا۟ بِـَٔايَـتِ ٱللَّـهِ ثَمَنًا قَلِيلًا فَصَدُّوا۟ عَن سَبِيلِهِۦٓ إِنَّهُمْ سَآءَ مَا كَانُوا۟ يَعْمَلُونَ", "Mereka menukarkan ayat-ayat Allah dengan harga yang sedikit (dari faedah-faedah dunia), lalu mereka menghalangi (dirinya dan orang-orang lain) dari agama Allah; sesungguhnya amatlah buruknya apa yang mereka telah kerjakan.", R.raw.taubah9));
        arrayList.add(new VerseActivity("Taubah", "﻿لَا يَرْقُبُونَ فِى مُؤْمِنٍ إِلًّا وَلَا ذِمَّةً وَأُو۟لَـٓئِكَ هُمُ ٱلْمُعْتَدُونَ", "Mereka tidak menghormati pertalian kerabat dan perjanjian terhadap orang-orang yang beriman, dan merekalah orang-orang yang menceroboh.", R.raw.taubah10));

        /*ayat 11-20*/
        arrayList.add(new VerseActivity("Taubah", "فَإِن تَابُوا۟ وَأَقَامُوا۟ ٱلصَّلَوةَ وَءَاتَوُا۟ ٱلزَّكَوةَ فَإِخْوَنُكُمْ فِى ٱلدِّينِ وَنُفَصِّلُ ٱلْـَٔايَـتِ لِقَوْمٍ يَعْلَمُونَ", "Oleh itu, jika mereka bertaubat (dari kekufuran), dan mendirikan sembahyang serta memberi zakat, maka mereka itu adalah saudara kamu yang seagama; dan Kami menjelaskan ayat-ayat keterangan Kami satu persatu bagi kaum yang mahu mengetahui.", R.raw.taubah11));
        arrayList.add(new VerseActivity("Taubah", "وَإِن نَّكَثُوٓا۟ أَيْمَـنَهُم مِّنۢ بَعْدِ عَهْدِهِمْ وَطَعَنُوا۟ فِى دِينِكُمْ فَقَـتِلُوٓا۟ أَئِمَّةَ ٱلْكُفْرِ إِنَّهُمْ لَآ أَيْمَـنَ لَهُمْ لَعَلَّهُمْ يَنتَهُونَ", "Dan jika mereka mencabuli sumpahnya sesudah mengikat perjanjian setia, dan mereka pula mencela agama kamu, maka perangilah ketua-ketua dan pemimpin-pemimpin kaum yang kafir itu, kerana sesungguhnya mereka tidak menghormati sumpah janjinya, supaya mereka berhenti (dari kekufuran dan bertaubat).", R.raw.taubah12));
        arrayList.add(new VerseActivity("Taubah", "﻿أَلَا تُقَـتِلُونَ قَوْمًا نَّكَثُوٓا۟ أَيْمَـنَهُمْ وَهَمُّوا۟ بِإِخْرَاجِ ٱلرَّسُولِ وَهُم بَدَءُوكُمْ أَوَّلَ مَرَّةٍ أَتَخْشَوْنَهُمْ فَٱللَّـهُ أَحَقُّ أَن تَخْشَوْهُ إِن كُنتُم مُّؤْمِنِينَ", "Mengapa kamu tidak memerangi suatu kaum yang telah mencabuli sumpah janjinya, dan mereka pula telah berazam hendak mengusir Rasulullah, dan merekalah juga yang mula-mula memerangi kamu? Tidak patut kamu takut kepada mereka (sehingga kamu tidak mahu memeranginya) kerana Allah jualah yang berhak kamu takuti (melanggar perintahNya), jika betul kamu orang-orang yang beriman?", R.raw.taubah13));
        arrayList.add(new VerseActivity("Taubah", "قَـتِلُوهُمْ يُعَذِّبْهُمُ ٱللَّـهُ بِأَيْدِيكُمْ وَيُخْزِهِمْ وَيَنصُرْكُمْ عَلَيْهِمْ وَيَشْفِ صُدُورَ قَوْمٍ مُّؤْمِنِينَ", "Perangilah mereka, nescaya Allah akan menyeksa mereka dengan (perantaraan) tangan kamu, dan Allah akan menghinakan mereka serta menolong kamu menewaskan mereka, dan Ia akan memuaskan hati orang-orang yang beriman.", R.raw.taubah14));
        arrayList.add(new VerseActivity("Taubah", "﻿وَيُذْهِبْ غَيْظَ قُلُوبِهِمْ وَيَتُوبُ ٱللَّـهُ عَلَى مَن يَشَآءُ وَٱللَّـهُ عَلِيمٌ حَكِيمٌ", "Dan Ia juga akan menghapuskan kemarahan hati orang-orang yang beriman itu, dan Allah akan menerima taubat orang-orang yang dikehendakiNya; dan (ingatlah) Allah Maha Mengetahui, lagi Maha Bijaksana.", R.raw.taubah15));
        arrayList.add(new VerseActivity("Taubah", "أَمْ حَسِبْتُمْ أَن تُتْرَكُوا۟ وَلَمَّا يَعْلَمِ ٱللَّـهُ ٱلَّذِينَ جَـهَدُوا۟ مِنكُمْ وَلَمْ يَتَّخِذُوا۟ مِن دُونِ ٱللَّـهِ وَلَا رَسُولِهِۦ وَلَا ٱلْمُؤْمِنِينَ وَلِيجَةً وَٱللَّـهُ خَبِيرٌۢ بِمَا تَعْمَلُونَ", "Adakah kamu menyangka, bahawa kamu akan dibiarkan (dalam keadaan kamu yang ada itu), padahal belum lagi terbukti kepada Allah (sebagaimana yang diketahuiNya) orang-orang yang berjihad di antara kamu dan yang tidak mengambil teman-teman rapat (untuk mencurahkan rahsia kepada mereka), selain daripada Allah dan RasulNya serta orang-orang yang beriman? Dan (ingatlah) Allah Maha Mengetahui secara mendalam akan apa yang kamu kerjakan.", R.raw.taubah16));
        arrayList.add(new VerseActivity("Taubah", "﻿مَا كَانَ لِلْمُشْرِكِينَ أَن يَعْمُرُوا۟ مَسَـجِدَ ٱللَّـهِ شَـهِدِينَ عَلَىٓ أَنفُسِهِم بِٱلْكُفْرِ أُو۟لَـٓئِكَ حَبِطَتْ أَعْمَـلُهُمْ وَفِى ٱلنَّارِ هُمْ خَـلِدُونَ", "Tidaklah layak orang-orang kafir musyrik itu memakmurkan (menghidupkan) masjid-masjid Allah, sedang mereka menjadi saksi (mengakui) akan kekufuran diri mereka sendiri. Mereka itu ialah orang-orang yang rosak binasa amal-amalnya dan mereka pula kekal di dalam neraka.", R.raw.taubah17));
        arrayList.add(new VerseActivity("Taubah", "﻿إِنَّمَا يَعْمُرُ مَسَـجِدَ ٱللَّـهِ مَنْ ءَامَنَ بِٱللَّـهِ وَٱلْيَوْمِ ٱلْـَٔاخِرِ وَأَقَامَ ٱلصَّلَوةَ وَءَاتَى ٱلزَّكَوةَ وَلَمْ يَخْشَ إِلَّا ٱللَّـهَ فَعَسَىٓ أُو۟لَـٓئِكَ أَن يَكُونُوا۟ مِنَ ٱلْمُهْتَدِينَ", "Hanyasanya yang layak memakmurkan (menghidupkan) masjid-masjid Allah itu ialah orang-orang yang beriman kepada Allah dan hari akhirat serta mendirikan sembahyang dan menunaikan zakat dan tidak takut melainkan kepada Allah, (dengan adanya sifat-sifat yang tersebut) maka adalah diharapkan mereka menjadi dari golongan yang mendapat petunjuk.", R.raw.taubah18));
        arrayList.add(new VerseActivity("Taubah", "﻿أَجَعَلْتُمْ سِقَايَةَ ٱلْحَآجِّ وَعِمَارَةَ ٱلْمَسْجِدِ ٱلْحَرَامِ كَمَنْ ءَامَنَ بِٱللَّـهِ وَٱلْيَوْمِ ٱلْـَٔاخِرِ وَجَـهَدَ فِى سَبِيلِ ٱللَّـهِ لَا يَسْتَوُۥنَ عِندَ ٱللَّـهِ وَٱللَّـهُ لَا يَهْدِى ٱلْقَوْمَ ٱلظَّـلِمِينَ", "Adakah kamu sifatkan hanya perbuatan memberi minum kepada orang-orang yang mengerjakan Haji, dan (hanya perbuatan) memakmurkan Masjid Al-Haraam itu sama seperti orang yang beriman kepada Allah dan hari akhirat serta berjihad pada jalan Allah? Mereka (yang bersifat demikian) tidak sama di sisi Allah, dan Allah tidak memberikan hidayah petunjuk kepada kaum yang zalim.", R.raw.taubah19));
        arrayList.add(new VerseActivity("Taubah", "﻿ٱلَّذِينَ ءَامَنُوا۟ وَهَاجَرُوا۟ وَجَـهَدُوا۟ فِى سَبِيلِ ٱللَّـهِ بِأَمْوَلِهِمْ وَأَنفُسِهِمْ أَعْظَمُ دَرَجَةً عِندَ ٱللَّـهِ وَأُو۟لَـٓئِكَ هُمُ ٱلْفَآئِزُونَ", "(Sesungguhnya) orang-orang yang beriman dan berhijrah serta berjihad pada jalan Allah dengan harta benda dan jiwa mereka adalah lebih besar dan tinggi darjatnya di sisi Allah (daripada orang-orang yang hanya memberi minum orang-orang Haji dan orang yang memakmurkan masjid sahaja); dan mereka itulah orang-orang yang berjaya.", R.raw.taubah20));

        /*ayat 21-30*/
        arrayList.add(new VerseActivity("Taubah", "يُبَشِّرُهُمْ رَبُّهُم بِرَحْمَةٍ مِّنْهُ وَرِضْوَنٍ وَجَنَّـتٍ لَّهُمْ فِيهَا نَعِيمٌ مُّقِيمٌ", "Mereka digembirakan oleh Tuhan mereka dengan pemberian rahmat daripadanya dan keredaan serta Syurga; mereka beroleh di dalam Syurga itu nikmat kesenangan yang kekal.", R.raw.taubah21));
        arrayList.add(new VerseActivity("Taubah", "﻿خَـلِدِينَ فِيهَآ أَبَدًا إِنَّ ٱللَّـهَ عِندَهُۥٓ أَجْرٌ عَظِيمٌ", "Mereka kekal di dalamnya selama-lamanya. Sesungguhnya Allah, menyediakan di sisiNya pahala yang besar.", R.raw.taubah22));
        arrayList.add(new VerseActivity("Taubah", "﻿يَـٓأَيُّهَا ٱلَّذِينَ ءَامَنُوا۟ لَا تَتَّخِذُوٓا۟ ءَابَآءَكُمْ وَإِخْوَنَكُمْ أَوْلِيَآءَ إِنِ ٱسْتَحَبُّوا۟ ٱلْكُفْرَ عَلَى ٱلْإِيمَـنِ وَمَن يَتَوَلَّهُم مِّنكُمْ فَأُو۟لَـٓئِكَ هُمُ ٱلظَّـلِمُونَ", "Wahai orang-orang yang beriman! Janganlah kamu menjadikan bapa-bapa kamu dan saudara-saudara kamu sebagai orang-orang yang didampingi jika mereka memilih kufur dengan meninggalkan iman; dan sesiapa di antara kamu yang menjadikan mereka orang-orang yang didampingi, maka merekalah orang-orang yang zalim.", R.raw.taubah23));
        arrayList.add(new VerseActivity("Taubah", "قُلْ إِن كَانَ ءَابَآؤُكُمْ وَأَبْنَآؤُكُمْ وَإِخْوَنُكُمْ وَأَزْوَجُكُمْ وَعَشِيرَتُكُمْ وَأَمْوَلٌ ٱقْتَرَفْتُمُوهَا وَتِجَـرَةٌ تَخْشَوْنَ كَسَادَهَا وَمَسَـكِنُ تَرْضَوْنَهَآ أَحَبَّ إِلَيْكُم مِّنَ ٱللَّـهِ وَرَسُولِهِۦ وَجِهَادٍ فِى سَبِيلِهِۦ فَتَرَبَّصُوا۟ حَتَّى يَأْتِىَ ٱللَّـهُ بِأَمْرِهِۦ وَٱللَّـهُ لَا يَهْدِى ٱلْقَوْمَ ٱلْفَـسِقِينَ", "Katakanlah (wahai Muhammad): \"Jika bapa-bapa kamu, dan anak-anak kamu, dan saudara-saudara kamu, dan isteri-isteri (atau suami-suami) kamu, dan kaum keluarga kamu, dan harta benda yang kamu usahakan, dan perniagaan yang kamu bimbang akan merosot, dan rumah-rumah tempat tinggal yang kamu sukai, - (jika semuanya itu) menjadi perkara-perkara yang kamu cintai lebih daripada Allah dan RasulNya dan (daripada) berjihad untuk agamaNya, maka tunggulah sehingga Allah mendatangkan keputusanNya (azab seksaNya); kerana Allah tidak akan memberi petunjuk kepada orang-orang yang fasik (derhaka).", R.raw.taubah24));
        arrayList.add(new VerseActivity("Taubah", "لَقَدْ نَصَرَكُمُ ٱللَّـهُ فِى مَوَاطِنَ كَثِيرَةٍ وَيَوْمَ حُنَيْنٍ إِذْ أَعْجَبَتْكُمْ كَثْرَتُكُمْ فَلَمْ تُغْنِ عَنكُمْ شَيْـًٔا وَضَاقَتْ عَلَيْكُمُ ٱلْأَرْضُ بِمَا رَحُبَتْ ثُمَّ وَلَّيْتُم مُّدْبِرِينَ", "Sesungguhnya Allah telah menolong kamu mencapai kemenangan dalam banyak medan-medan perang dan di medan perang Hunain, iaitu semasa kamu merasa megah dengan sebab bilangan kamu yang ramai; maka bilangan yang ramai itu tidak mendatangkan faedah kepada kamu sedikitpun; dan (semasa kamu merasa) bumi yang luas itu menjadi sempit kepada kamu; kemudian kamu berpaling undur melarikan diri.", R.raw.taubah25));
        arrayList.add(new VerseActivity("Taubah", "ثُمَّ أَنزَلَ ٱللَّـهُ سَكِينَتَهُۥ عَلَى رَسُولِهِۦ وَعَلَى ٱلْمُؤْمِنِينَ وَأَنزَلَ جُنُودًا لَّمْ تَرَوْهَا وَعَذَّبَ ٱلَّذِينَ كَفَرُوا۟ وَذَلِكَ جَزَآءُ ٱلْكَـفِرِينَ", "Kemudian Allah menurunkan semangat tenang tenteram kepada RasulNya dan kepada orang-orang yang beriman, dan Allah menurunkan tentera yang kamu tidak melihatnya, serta Ia menyeksa orang-orang kafir itu (dengan kekalahan yang membawa kehancuran); dan yang demikian itu ialah balasan bagi orang-orang yang kafir.", R.raw.taubah26));
        arrayList.add(new VerseActivity("Taubah", "﻿ثُمَّ يَتُوبُ ٱللَّـهُ مِنۢ بَعْدِ ذَلِكَ عَلَى مَن يَشَآءُ وَٱللَّـهُ غَفُورٌ رَّحِيمٌ", "Kemudian Allah menerima taubat orang-orang yang dikehendaki (dengan memberi taufiq untuk memeluk Islam), sesudah (orang-orang kafir itu ditimpakan dengan azab); dan (ingatlah) Allah Maha Pengampun, lagi Maha Mengasihani.", R.raw.taubah27));
        arrayList.add(new VerseActivity("Taubah", "يَـٓأَيُّهَا ٱلَّذِينَ ءَامَنُوٓا۟ إِنَّمَا ٱلْمُشْرِكُونَ نَجَسٌ فَلَا يَقْرَبُوا۟ ٱلْمَسْجِدَ ٱلْحَرَامَ بَعْدَ عَامِهِمْ هَـذَا وَإِنْ خِفْتُمْ عَيْلَةً فَسَوْفَ يُغْنِيكُمُ ٱللَّـهُ مِن فَضْلِهِۦٓ إِن شَآءَ إِنَّ ٱللَّـهَ عَلِيمٌ حَكِيمٌ", "Wahai orang-orang yang beriman! Sesungguhnya (kepercayaan) orang-orang kafir musyrik itu najis, oleh itu janganlah mereka menghampiri Masjid Al-Haraam sesudah tahun ini; dan jika kamu bimbangkan kepapaan, maka Allah akan memberi kekayaan kepada kamu dari limpah kurniaNya, jika dia kehendaki. Sesungguhnya Allah Maha Mengetahui, lagi Maha Bijaksana.", R.raw.taubah28));
        arrayList.add(new VerseActivity("Taubah", "قَـتِلُوا۟ ٱلَّذِينَ لَا يُؤْمِنُونَ بِٱللَّـهِ وَلَا بِٱلْيَوْمِ ٱلْـَٔاخِرِ وَلَا يُحَرِّمُونَ مَا حَرَّمَ ٱللَّـهُ وَرَسُولُهُۥ وَلَا يَدِينُونَ دِينَ ٱلْحَقِّ مِنَ ٱلَّذِينَ أُوتُوا۟ ٱلْكِتَـبَ حَتَّى يُعْطُوا۟ ٱلْجِزْيَةَ عَن يَدٍ وَهُمْ صَـغِرُونَ", "Perangilah orang-orang yang tidak beriman kepada Allah dan tidak beriman kepada hari akhirat, dan mereka pula tidak mengharamkan apa yang telah diharamkan oleh Allah dan RasulNya, dan tidak beragama dengan agama yang benar, iaitu dari orang-orang yang diberikan Kitab (kaum Yahudi dan Nasrani), sehingga mereka membayar \"Jizyah\" dengan keadaan taat dan merendah diri.", R.raw.taubah29));
        arrayList.add(new VerseActivity("Taubah", "وَقَالَتِ ٱلْيَهُودُ عُزَيْرٌ ٱبْنُ ٱللَّـهِ وَقَالَتِ ٱلنَّصَـرَى ٱلْمَسِيحُ ٱبْنُ ٱللَّـهِ ذَلِكَ قَوْلُهُم بِأَفْوَهِهِمْ يُضَـهِـُٔونَ قَوْلَ ٱلَّذِينَ كَفَرُوا۟ مِن قَبْلُ قَـتَلَهُمُ ٱللَّـهُ أَنَّى يُؤْفَكُونَ", "Dan orang-orang Yahudi berkata: \"Uzair ialah anak Allah\" dan orang-orang Nasrani berkata: \"Al-Masih ialah anak Allah\". Demikianlah perkataan mereka dengan mulut mereka sendiri, (iaitu) mereka menyamai perkataan orang-orang kafir dahulu; semoga Allah binasakan mereka. Bagaimanakah mereka boleh berpaling dari kebenaran?", R.raw.taubah30));

        /*ayat 31-40*/
        arrayList.add(new VerseActivity("Taubah", "ٱتَّخَذُوٓا۟ أَحْبَارَهُمْ وَرُهْبَـنَهُمْ أَرْبَابًا مِّن دُونِ ٱللَّـهِ وَٱلْمَسِيحَ ٱبْنَ مَرْيَمَ وَمَآ أُمِرُوٓا۟ إِلَّا لِيَعْبُدُوٓا۟ إِلَـهًا وَحِدًا لَّآ إِلَـهَ إِلَّا هُوَ سُبْحَـنَهُۥ عَمَّا يُشْرِكُونَ", "Mereka menjadikan pendita-pendita dan ahli-ahli agama mereka sebagai pendidik-pendidik selain dari Allah, dan juga (mereka mempertuhankan) Al-Masih ibni Maryam, padahal mereka tidak diperintahkan melainkan untuk menyembah Tuhan Yang Maha Esa; tiada Tuhan (yang berhak disembah) melainkan Dia. Maha Suci Allah dari apa yang mereka sekutukan.", R.raw.taubah31));
        arrayList.add(new VerseActivity("Taubah", "يُرِيدُونَ أَن يُطْفِـُٔوا۟ نُورَ ٱللَّـهِ بِأَفْوَهِهِمْ وَيَأْبَى ٱللَّـهُ إِلَّآ أَن يُتِمَّ نُورَهُۥ وَلَوْ كَرِهَ ٱلْكَـفِرُونَ", "Mereka hendak memadamkan cahaya Allah (agama Islam) dengan mulut mereka, sedang Allah tidak menghendaki melainkan menyempurnakan cahayaNya, sekalipun orang-orang kafir tidak suka (akan yang demikian).", R.raw.taubah32));
        arrayList.add(new VerseActivity("Taubah", "هُوَ ٱلَّذِىٓ أَرْسَلَ رَسُولَهُۥ بِٱلْهُدَى وَدِينِ ٱلْحَقِّ لِيُظْهِرَهُۥ عَلَى ٱلدِّينِ كُلِّهِۦ وَلَوْ كَرِهَ ٱلْمُشْرِكُونَ", "Dia lah yang telah mengutus RasulNya (Muhammad) dengan membawa petunjuk dan agama yang benar (agama Islam), untuk dimenangkan dan ditinggikannya atas segala agama yang lain, walaupun orang-orang musyrik tidak menyukainya.", R.raw.taubah33));
        arrayList.add(new VerseActivity("Taubah", "﻿يَـٓأَيُّهَا ٱلَّذِينَ ءَامَنُوٓا۟ إِنَّ كَثِيرًا مِّنَ ٱلْأَحْبَارِ وَٱلرُّهْبَانِ لَيَأْكُلُونَ أَمْوَلَ ٱلنَّاسِ بِٱلْبَـطِلِ وَيَصُدُّونَ عَن سَبِيلِ ٱللَّـهِ وَٱلَّذِينَ يَكْنِزُونَ ٱلذَّهَبَ وَٱلْفِضَّةَ وَلَا يُنفِقُونَهَا فِى سَبِيلِ ٱللَّـهِ فَبَشِّرْهُم بِعَذَابٍ أَلِيمٍ", "Wahai orang-orang yang beriman! Sesungguhnya banyak di antara pendita-pendita dan ahli-ahli agama (Yahudi dan Nasrani) memakan harta orang ramai dengan cara yang salah, dan mereka menghalangi (manusia) dari jalan Allah (agama Islam). Dan (ingatlah) orang-orang yang menyimpan emas dan perak serta tidak membelanjakannya pada jalan Allah, maka khabarkanlah kepada mereka dengan (balasan) azab seksa yang tidak terperi sakitnya.", R.raw.taubah34));
        arrayList.add(new VerseActivity("Taubah", "﻿يَوْمَ يُحْمَى عَلَيْهَا فِى نَارِ جَهَنَّمَ فَتُكْوَى بِهَا جِبَاهُهُمْ وَجُنُوبُهُمْ وَظُهُورُهُمْ هَـذَا مَا كَنَزْتُمْ لِأَنفُسِكُمْ فَذُوقُوا۟ مَا كُنتُمْ تَكْنِزُونَ", "(Iaitu) pada hari dibakar emas perak (dan harta benda) itu dalam neraka jahanam, lalu diselar dengannya dahi mereka, dan rusuk mereka, serta belakang mereka (sambil dikatakan kepada mereka): \"Inilah apa yang telah kamu simpan untuk diri kamu sendiri, oleh itu rasalah (azab dari) apa yang kamu simpan itu.", R.raw.taubah35));
        arrayList.add(new VerseActivity("Taubah", "إِنَّ عِدَّةَ ٱلشُّهُورِ عِندَ ٱللَّـهِ ٱثْنَا عَشَرَ شَهْرًا فِى كِتَـبِ ٱللَّـهِ يَوْمَ خَلَقَ ٱلسَّمَـوَتِ وَٱلْأَرْضَ مِنْهَآ أَرْبَعَةٌ حُرُمٌ ذَلِكَ ٱلدِّينُ ٱلْقَيِّمُ فَلَا تَظْلِمُوا۟ فِيهِنَّ أَنفُسَكُمْ وَقَـتِلُوا۟ ٱلْمُشْرِكِينَ كَآفَّةً كَمَا يُقَـتِلُونَكُمْ كَآفَّةً وَٱعْلَمُوٓا۟ أَنَّ ٱللَّـهَ مَعَ ٱلْمُتَّقِينَ", "Sesungguhnya bilangan bulan-bulan di sisi (hukum) Allah ialah dua belas bulan, (yang telah ditetapkan) dalam Kitab Allah semasa Ia menciptakan langit dan bumi, di antaranya empat bulan yang dihormati. Ketetapan yang demikian itu ialah agama yang betul lurus, maka janganlah kamu menganiaya diri kamu dalam bulan-bulan yang dihormati itu (dengan melanggar laranganNya); dan perangilah kaum kafir musyrik seluruhnya sebagaimana mereka memerangi kamu seluruhnya; dan ketahuilah sesungguhnya Allah beserta orang-orang yang bertaqwa.", R.raw.taubah36));
        arrayList.add(new VerseActivity("Taubah", "إِنَّمَا ٱلنَّسِىٓءُ زِيَادَةٌ فِى ٱلْكُفْرِ يُضَلُّ بِهِ ٱلَّذِينَ كَفَرُوا۟ يُحِلُّونَهُۥ عَامًا وَيُحَرِّمُونَهُۥ عَامًا لِّيُوَاطِـُٔوا۟ عِدَّةَ مَا حَرَّمَ ٱللَّـهُ فَيُحِلُّوا۟ مَا حَرَّمَ ٱللَّـهُ زُيِّنَ لَهُمْ سُوٓءُ أَعْمَـلِهِمْ وَٱللَّـهُ لَا يَهْدِى ٱلْقَوْمَ ٱلْكَـفِرِينَ", "Sesungguhnya perbuatan mengundurkan (kehormatan itu dari satu bulan ke satu bulan yang lain) adalah menambah kekufuran yang menjadikan orang-orang kafir itu tersesat kerananya. Mereka menghalalkannya pada satu tahun dan mengharamkannya pada tahun yang lain, supaya mereka dapat menyesuaikan bilangan (bulan-bulan yang empat) yang telah diharamkan Allah (berperang di dalamnya); dengan itu mereka menghalalkan apa yang telah diharamkan oleh Allah. Perbuatan buruk mereka itu dihias dan dijadikan indah (oleh Syaitan) untuk dipandang baik oleh mereka. Dan (ingatlah) Allah tidak memberi hidayah petunjuk kepada orang-orang yang kafir.", R.raw.taubah37));
        arrayList.add(new VerseActivity("Taubah", "يَـٓأَيُّهَا ٱلَّذِينَ ءَامَنُوا۟ مَا لَكُمْ إِذَا قِيلَ لَكُمُ ٱنفِرُوا۟ فِى سَبِيلِ ٱللَّـهِ ٱثَّاقَلْتُمْ إِلَى ٱلْأَرْضِ أَرَضِيتُم بِٱلْحَيَوةِ ٱلدُّنْيَا مِنَ ٱلْـَٔاخِرَةِ فَمَا مَتَـعُ ٱلْحَيَوةِ ٱلدُّنْيَا فِى ٱلْـَٔاخِرَةِ إِلَّا قَلِيلٌ", "Wahai orang-orang yang beriman! Mengapa kamu, apabila dikatakan kepada kamu: \"Pergilah beramai-ramai untuk berperang pada jalan Allah\", kamu merasa keberatan (dan suka tinggal menikmati kesenangan) di tempat (masing-masing)? Adakah kamu lebih suka dengan kehidupan dunia daripada akhirat? (Kesukaan kamu itu salah) kerana kesenangan hidup di dunia ini hanya sedikit jua berbanding dengan (kesenangan hidup) di akhirat kelak.", R.raw.taubah38));
        arrayList.add(new VerseActivity("Taubah", "﻿إِلَّا تَنفِرُوا۟ يُعَذِّبْكُمْ عَذَابًا أَلِيمًا وَيَسْتَبْدِلْ قَوْمًا غَيْرَكُمْ وَلَا تَضُرُّوهُ شَيْـًٔا وَٱللَّـهُ عَلَى كُلِّ شَىْءٍ قَدِيرٌ", "Jika kamu tidak pergi beramai-ramai (untuk berperang pada jalan Allah - membela agamaNya), Allah akan menyeksa kamu dengan azab seksa yang tidak terperi sakitnya dan Ia akan menggantikan kamu dengan kaum yang lain, dan kamu tidak akan dapat mendatangkan bahaya sedikitpun kepadaNya. Dan (ingatlah) Allah Maha Kuasa atas tiap-tiap sesuatu.", R.raw.taubah39));
        arrayList.add(new VerseActivity("Taubah", "إِلَّا تَنصُرُوهُ فَقَدْ نَصَرَهُ ٱللَّـهُ إِذْ أَخْرَجَهُ ٱلَّذِينَ كَفَرُوا۟ ثَانِىَ ٱثْنَيْنِ إِذْ هُمَا فِى ٱلْغَارِ إِذْ يَقُولُ لِصَـحِبِهِۦ لَا تَحْزَنْ إِنَّ ٱللَّـهَ مَعَنَا فَأَنزَلَ ٱللَّـهُ سَكِينَتَهُۥ عَلَيْهِ وَأَيَّدَهُۥ بِجُنُودٍ لَّمْ تَرَوْهَا وَجَعَلَ كَلِمَةَ ٱلَّذِينَ كَفَرُوا۟ ٱلسُّفْلَى وَكَلِمَةُ ٱللَّـهِ هِىَ ٱلْعُلْيَا وَٱللَّـهُ عَزِيزٌ حَكِيمٌ", "Kalau kamu tidak menolongnya (Nabi Muhammad) maka sesungguhnya Allah telahpun menolongnya, iaitu ketika kaum kafir (di Makkah) mengeluarkannya (dari negerinya Makkah) sedang ia salah seorang dari dua (sahabat) semasa mereka berlindung di dalam gua, ketika ia berkata kepada sahabatnya: \"Janganlah engkau berdukacita, sesungguhnya Allah bersama kita\". Maka Allah menurunkan semangat tenang tenteram kepada (Nabi Muhammad) dan menguatkannya dengan bantuan tentera (malaikat) yang kamu tidak melihatnya. Dan Allah menjadikan seruan (syirik) orang-orang kafir terkebawah (kalah dengan sehina-hinanya), dan Kalimah Allah (Islam) ialah yang tertinggi (selama-lamanya), kerana Allah Maha Kuasa, lagi Maha Bijaksana.", R.raw.taubah40));

        /*ayat 41-50*/
        arrayList.add(new VerseActivity("Taubah", "﻿ٱنفِرُوا۟ خِفَافًا وَثِقَالًا وَجَـهِدُوا۟ بِأَمْوَلِكُمْ وَأَنفُسِكُمْ فِى سَبِيلِ ٱللَّـهِ ذَلِكُمْ خَيْرٌ لَّكُمْ إِن كُنتُمْ تَعْلَمُونَ", "Pergilah kamu beramai-ramai (untuk berperang pada jalan Allah), sama ada dengan keadaan ringan (dan mudah bergerak) ataupun dengan keadaan berat (disebabkan berbagai-bagai tanggungjawab); dan berjihadlah dengan harta benda dan jiwa kamu pada jalan Allah (untuk membela Islam). Yang demikian amatlah baik bagi kamu, jika kamu mengetahui.", R.raw.taubah41));
        arrayList.add(new VerseActivity("Taubah", "لَوْ كَانَ عَرَضًا قَرِيبًا وَسَفَرًا قَاصِدًا لَّٱتَّبَعُوكَ وَلَـكِنۢ بَعُدَتْ عَلَيْهِمُ ٱلشُّقَّةُ وَسَيَحْلِفُونَ بِٱللَّـهِ لَوِ ٱسْتَطَعْنَا لَخَرَجْنَا مَعَكُمْ يُهْلِكُونَ أَنفُسَهُمْ وَٱللَّـهُ يَعْلَمُ إِنَّهُمْ لَكَـذِبُونَ", "Kalau apa yang engkau serukan kepada mereka (wahai Muhammad) sesuatu yang berfaedah yang sudah didapati, dan satu perjalanan yang sederhana (tidak begitu jauh), nescaya mereka (yang munafik itu) akan mengikutmu; tetapi tempat yang hendak dituju itu jauh bagi mereka. Dan mereka akan bersumpah dengan nama Allah dengan berkata: \"Kalau kami sanggup, tentulah kami akan pergi bersama kamu\". (Dengan sumpah dusta itu) mereka membinasakan diri mereka sendiri, sedang Allah mengetahui bahawa sesungguhnya mereka itu orang-orang yang berdusta (tentang tidak sanggupnya mengikutmu).", R.raw.taubah42));
        arrayList.add(new VerseActivity("Taubah", "﻿عَفَا ٱللَّهُ عَنكَ لِمَ أَذِنتَ لَهُمْ حَتَّىٰ يَتَبَيَّنَ لَكَ ٱلَّذِينَ صَدَقُوا۟ وَتَعْلَمَ ٱلْكَٰذِبِينَ", "Allah memaafkanmu (wahai Muhammad), mengapa engkau izinkan mereka (tidak turut berperang) sebelum nyata bagimu orang-orang yang benar dan (sebelum) engkau mengetahui orang-orang yang berdusta?", R.raw.taubah43));
        arrayList.add(new VerseActivity("Taubah", "لَا يَسْتَـْٔذِنُكَ ٱلَّذِينَ يُؤْمِنُونَ بِٱللَّهِ وَٱلْيَوْمِ ٱلْءَاخِرِ أَن يُجَٰهِدُوا۟ بِأَمْوَٰلِهِمْ وَأَنفُسِهِمْ ۗ وَٱللَّهُ عَلِيمٌۢ بِٱلْمُتَّقِينَ", "Orang-orang yang beriman kepada Allah dan hari akhirat, tidak akan meminta izin kepadamu untuk (tidak turut) berjihad dengan harta benda dan jiwa mereka. Dan (ingatlah) Allah Maha Mengetahui akan orang-orang yang bertaqwa.", R.raw.taubah44));
        arrayList.add(new VerseActivity("Taubah", "﻿إِنَّمَا يَسْتَـْٔذِنُكَ ٱلَّذِينَ لَا يُؤْمِنُونَ بِٱللَّهِ وَٱلْيَوْمِ ٱلْءَاخِرِ وَٱرْتَابَتْ قُلُوبُهُمْ فَهُمْ فِى رَيْبِهِمْ يَتَرَدَّدُونَ", "Sesungguhnya yang akan meminta izin kepadamu hanyalah orang-orang yang tidak beriman kepada Allah dan hari akhirat, dan yang hati mereka (sangat) ragu-ragu. Oleh itu mereka sentiasa bingung teragak-agak dalam keraguannya.", R.raw.taubah45));
        arrayList.add(new VerseActivity("Taubah", "۞ وَلَوْ أَرَادُوا۟ ٱلْخُرُوجَ لَأَعَدُّوا۟ لَهُۥ عُدَّةً وَلَٰكِن كَرِهَ ٱللَّهُ ٱنۢبِعَاثَهُمْ فَثَبَّطَهُمْ وَقِيلَ ٱقْعُدُوا۟ مَعَ ٱلْقَٰعِدِينَ", "Dan kalaulah mereka mahu keluar (untuk turut berperang), tentulah mereka menyediakan persiapan untuknya; tetapi Allah tidak suka pemergian mereka, lalu dilemahkanNya semangat mereka, dan dikatakan (oleh Syaitan): \"Tinggallah kamu bersama-sama orang-orang yang tinggal\".", R.raw.taubah46));
        arrayList.add(new VerseActivity("Taubah", "﻿لَوْ خَرَجُوا۟ فِيكُم مَّا زَادُوكُمْ إِلَّا خَبَالًا وَلَأَوْضَعُوا۟ خِلَٰلَكُمْ يَبْغُونَكُمُ ٱلْفِتْنَةَ وَفِيكُمْ سَمَّٰعُونَ لَهُمْ ۗ وَٱللَّهُ عَلِيمٌۢ بِٱلظَّٰلِمِينَ", "Kalaulah mereka keluar bersama kamu, tidaklah mereka menambahkan kamu melainkan kerosakan, dan tentulah mereka segera menjalankan hasutan di antara kamu, (dengan tujuan) hendak menimbulkan fitnah (kekacauan) dalam kalangan kamu; sedang di antara kamu ada orang yang suka mendengar hasutan mereka. Dan (ingatlah) Allah Maha Mengetahui akan orang-orang yang zalim.", R.raw.taubah47));
        arrayList.add(new VerseActivity("Taubah", "لَقَدِ ٱبْتَغَوُا۟ ٱلْفِتْنَةَ مِن قَبْلُ وَقَلَّبُوا۟ لَكَ ٱلْأُمُورَ حَتَّىٰ جَآءَ ٱلْحَقُّ وَظَهَرَ أَمْرُ ٱللَّهِ وَهُمْ كَٰرِهُونَ", "Sesungguhnya mereka telah lakukan fitnah semenjak dahulu lagi, dan mereka merancangkan terhadapmu (wahai Muhammad) berbagai tipu daya, sehingga datanglah kebenaran, dan nyatalah (kemenangan) agama Allah (Islam), sedang mereka tidak suka kepadanya.", R.raw.taubah48));
        arrayList.add(new VerseActivity("Taubah", "وَمِنْهُم مَّن يَقُولُ ٱئْذَن لِّى وَلَا تَفْتِنِّىٓ ۚ أَلَا فِى ٱلْفِتْنَةِ سَقَطُوا۟ ۗ وَإِنَّ جَهَنَّمَ لَمُحِيطَةٌۢ بِٱلْكَٰفِرِينَ", "Dan di antara mereka (yang munafik itu) ada yang berkata: \"Izinkanlah aku (supaya tidak pergi berperang) dan janganlah engkau menjadikan daku dipengaruhi oleh fitnah \". Ketahuilah, mereka telah pun tercebur ke dalam fitnah (dengan dalihan yang dusta itu). Dan sesungguhnya azab Jahannam meliputi orang-orang yang kafir.", R.raw.taubah49));
        arrayList.add(new VerseActivity("Taubah", "إِن تُصِبْكَ حَسَنَةٌ تَسُؤْهُمْ ۖ وَإِن تُصِبْكَ مُصِيبَةٌ يَقُولُوا۟ قَدْ أَخَذْنَآ أَمْرَنَا مِن قَبْلُ وَيَتَوَلَّوا۟ وَّهُمْ فَرِحُونَ", "Jika engkau (wahai Muhammad) beroleh sesuatu kebaikan, (maka) kebaikan itu menyebabkan mereka sakit hati; dan jika engkau ditimpa sesuatu bencana, mereka berkata: \"Sesungguhnya kami telahpun mengambil keputusan (tidak turut berperang) sebelum itu\", dan mereka berpaling (meninggalkanmu) sambil mereka bergembira.", R.raw.taubah50));

        /*ayat 51-60*/
        arrayList.add(new VerseActivity("Taubah", "قُل لَّن يُصِيبَنَآ إِلَّا مَا كَتَبَ ٱللَّهُ لَنَا هُوَ مَوْلَىٰنَا ۚ وَعَلَى ٱللَّهِ فَلْيَتَوَكَّلِ ٱلْمُؤْمِنُونَ", "Katakanlah (wahai Muhammad): \"Tidak sekali-kali akan menimpa kami sesuatu pun melainkan apa yang telah ditetapkan Allah bagi kami. Dia lah Pelindung yang menyelamatkan kami, dan (dengan kepercayaan itu) maka kepada Allah jualah hendaknya orang-orang yang beriman bertawakal\".", R.raw.taubah51));
        arrayList.add(new VerseActivity("Taubah", "﻿قُلْ هَلْ تَرَبَّصُونَ بِنَآ إِلَّآ إِحْدَى ٱلْحُسْنَيَيْنِ ۖ وَنَحْنُ نَتَرَبَّصُ بِكُمْ أَن يُصِيبَكُمُ ٱللَّهُ بِعَذَابٍ مِّنْ عِندِهِۦٓ أَوْ بِأَيْدِينَا ۖ فَتَرَبَّصُوٓا۟ إِنَّا مَعَكُم مُّتَرَبِّصُونَ", "Katakanlah: \"(Sebenarnya) tidak ada yang kamu tunggu-tunggu untuk kami melainkan salah satu dari dua perkara yang sebaik-baiknya (iaitu kemenangan atau mati syahid); dan kami menunggu-nunggu pula untuk kamu bahawa Allah akan menimpakan kamu dengan azab dari sisiNya, atau dengan perantaraan tangan kami. Oleh itu tunggulah, sesungguhnya kami juga menunggu bersama-sama kamu\".", R.raw.taubah52));
        arrayList.add(new VerseActivity("Taubah", "قُلْ أَنفِقُوا۟ طَوْعًا أَوْ كَرْهًا لَّن يُتَقَبَّلَ مِنكُمْ ۖ إِنَّكُمْ كُنتُمْ قَوْمًا فَٰسِقِينَ", "Katakanlah: \"Dermakanlah harta kamu sama ada dengan sukarela atau kerana terpaksa, tidak sekali-kali akan diterima daripada kamu, (kerana) sesungguhnya kamu adalah orang-orang yang fasik\".", R.raw.taubah53));
        arrayList.add(new VerseActivity("Taubah", "وَمَا مَنَعَهُمْ أَن تُقْبَلَ مِنْهُمْ نَفَقَٰتُهُمْ إِلَّآ أَنَّهُمْ كَفَرُوا۟ بِٱللَّهِ وَبِرَسُولِهِۦ وَلَا يَأْتُونَ ٱلصَّلَوٰةَ إِلَّا وَهُمْ كُسَالَىٰ وَلَا يُنفِقُونَ إِلَّا وَهُمْ كَٰرِهُونَ", "Dan tidak ada yang menghalangi mereka, untuk diterima derma-derma mereka melainkan kerana mereka kufur kepada Allah dan RasulNya, dan (kerana) mereka tidak mengerjakan sembahyang melainkan dengan keadaan malas dan mereka pula tidak mendermakan hartanya melainkan dengan perasaan benci.", R.raw.taubah54));
        arrayList.add(new VerseActivity("Taubah", "فَلَا تُعْجِبْكَ أَمْوَٰلُهُمْ وَلَآ أَوْلَٰدُهُمْ ۚ إِنَّمَا يُرِيدُ ٱللَّهُ لِيُعَذِّبَهُم بِهَا فِى ٱلْحَيَوٰةِ ٱلدُّنْيَا وَتَزْهَقَ أَنفُسُهُمْ وَهُمْ كَٰفِرُونَ", "Oleh itu, janganlah engkau tertarik hati kepada harta benda dan anak-anak mereka, (kerana) sesungguhnya Allah hanya hendak menyeksa mereka dengan harta benda dan anak-anak itu dalam kehidupan dunia, dan hendak menjadikan nyawa mereka tercabut sedang mereka berkeadaan kafir (untuk mendapat azab akhirat pula).", R.raw.taubah55));
        arrayList.add(new VerseActivity("Taubah", "﻿وَيَحْلِفُونَ بِٱللَّهِ إِنَّهُمْ لَمِنكُمْ وَمَا هُم مِّنكُمْ وَلَٰكِنَّهُمْ قَوْمٌ يَفْرَقُونَ", "Dan mereka (yang munafik itu) bersumpah dengan nama Allah bahawa sesungguhnya mereka dari golongan kamu, padahal mereka bukanlah dari golongan kamu, tetapi mereka ialah suatu kaum yang pengecut.", R.raw.taubah56));
        arrayList.add(new VerseActivity("Taubah", "لَوْ يَجِدُونَ مَلْجَـًٔا أَوْ مَغَٰرَٰتٍ أَوْ مُدَّخَلًا لَّوَلَّوْا۟ إِلَيْهِ وَهُمْ يَجْمَحُونَ", "Kalau mereka dapat tempat perlindungan, atau gua-gua, atau lubang-lubang dalam tanah, nescaya mereka segera menuju ke arahnya serta melompat masuk ke dalamnya.", R.raw.taubah57));
        arrayList.add(new VerseActivity("Taubah", "وَمِنْهُم مَّن يَلْمِزُكَ فِى ٱلصَّدَقَٰتِ فَإِنْ أُعْطُوا۟ مِنْهَا رَضُوا۟ وَإِن لَّمْ يُعْطَوْا۟ مِنْهَآ إِذَا هُمْ يَسْخَطُونَ", "Dan di antara mereka ada yang mencelamu (wahai Muhammad) mengenai (pembahagian) sedekah-sedekah (zakat); oleh itu jika mereka diberikan sebahagian daripadanya (menurut kehendak mereka), mereka suka (dan memandangnya adil); dan jika mereka tidak diberikan dari zakat itu (menurut kehendaknya), (maka) dengan serta merta mereka marah.", R.raw.taubah58));
        arrayList.add(new VerseActivity("Taubah", "﻿وَلَوْ أَنَّهُمْ رَضُوا۟ مَآ ءَاتَىٰهُمُ ٱللَّهُ وَرَسُولُهُۥ وَقَالُوا۟ حَسْبُنَا ٱللَّهُ سَيُؤْتِينَا ٱللَّهُ مِن فَضْلِهِۦ وَرَسُولُهُۥٓ إِنَّآ إِلَى ٱللَّهِ رَٰغِبُونَ", "Dan (amatlah baiknya) kalau mereka berpuas hati dengan apa yang diberikan oleh Allah dan RasulNya kepada mereka, sambil mereka berkata: \"Cukuplah Allah bagi kami; Allah akan memberi kepada kami dari limpah kurniaNya, demikian juga RasulNya; sesungguhnya kami sentiasa berharap kepada Allah\"", R.raw.taubah59));
        arrayList.add(new VerseActivity("Taubah", "﻿۞ إِنَّمَا ٱلصَّدَقَٰتُ لِلْفُقَرَآءِ وَٱلْمَسَٰكِينِ وَٱلْعَٰمِلِينَ عَلَيْهَا وَٱلْمُؤَلَّفَةِ قُلُوبُهُمْ وَفِى ٱلرِّقَابِ وَٱلْغَٰرِمِينَ وَفِى سَبِيلِ ٱللَّهِ وَٱبْنِ ٱلسَّبِيلِ ۖ فَرِيضَةً مِّنَ ٱللَّهِ ۗ وَٱللَّهُ عَلِيمٌ حَكِيمٌ", "Sesungguhnya sedekah-sedekah (zakat) itu hanyalah untuk orang-orang fakir, dan orang-orang miskin, dan amil-amil yang mengurusnya, dan orang-orang muallaf yang dijinakkan hatinya, dan untuk hamba-hamba yang hendak memerdekakan dirinya, dan orang-orang yang berhutang, dan untuk (dibelanjakan pada) jalan Allah, dan orang-orang musafir (yang keputusan) dalam perjalanan. (Ketetapan hukum yang demikian itu ialah) sebagai satu ketetapan (yang datangnya) dari Allah. Dan (ingatlah) Allah Maha Mengetahui, lagi Maha Bijaksana.", R.raw.taubah60));

        /*ayat 61-70*/
        arrayList.add(new VerseActivity("Taubah", "وَمِنْهُمُ ٱلَّذِينَ يُؤْذُونَ ٱلنَّبِىَّ وَيَقُولُونَ هُوَ أُذُنٌ ۚ قُلْ أُذُنُ خَيْرٍ لَّكُمْ يُؤْمِنُ بِٱللَّهِ وَيُؤْمِنُ لِلْمُؤْمِنِينَ وَرَحْمَةٌ لِّلَّذِينَ ءَامَنُوا۟ مِنكُمْ ۚ وَٱلَّذِينَ يُؤْذُونَ رَسُولَ ٱللَّهِ لَهُمْ عَذَابٌ أَلِيمٌ", "Dan di antara mereka (yang munafik itu) ada orang-orang yang menyakiti Nabi sambil mereka berkata: \"Bahawa dia (Nabi Muhammad) orang yang suka mendengar (dan percaya pada apa yang didengarnya)\". Katakanlah: \"Dia mendengar (dan percaya) apa yang baik bagi kamu, ia beriman kepada Allah dan percaya kepada orang mukmin, dan ia pula menjadi rahmat bagi orang-orang yang beriman di antara kamu\". Dan orang-orang yang menyakiti Rasulullah itu, bagi mereka azab seksa yang tidak terperi sakitnya.", R.raw.taubah61));
        arrayList.add(new VerseActivity("Taubah", "﻿يَحْلِفُونَ بِٱللَّهِ لَكُمْ لِيُرْضُوكُمْ وَٱللَّهُ وَرَسُولُهُۥٓ أَحَقُّ أَن يُرْضُوهُ إِن كَانُوا۟ مُؤْمِنِينَ", "Mereka bersumpah kepada kamu dengan nama Allah untuk mendapat keredaan kamu, padahal Allah dan RasulNya jualah yang lebih berhak mereka mendapat keredaanNya, jika betul mereka orang-orang yang beriman.", R.raw.taubah62));
        arrayList.add(new VerseActivity("Taubah", "أَلَمْ يَعْلَمُوٓا۟ أَنَّهُۥ مَن يُحَادِدِ ٱللَّهَ وَرَسُولَهُۥ فَأَنَّ لَهُۥ نَارَ جَهَنَّمَ خَٰلِدًا فِيهَا ۚ ذَٰلِكَ ٱلْخِزْىُ ٱلْعَظِيمُ", "Tidakkah mereka mengetahui bahawa sesiapa yang menentang (perintah-perintah) Allah dan RasulNya, maka sesungguhnya adalah baginya neraka Jahannam serta ia kekal di dalamnya? Balasan yang demikian adalah kehinaan yang besar", R.raw.taubah63));
        arrayList.add(new VerseActivity("Taubah", "يَحْذَرُ ٱلْمُنَٰفِقُونَ أَن تُنَزَّلَ عَلَيْهِمْ سُورَةٌ تُنَبِّئُهُم بِمَا فِى قُلُوبِهِمْ ۚ قُلِ ٱسْتَهْزِءُوٓا۟ إِنَّ ٱللَّهَ مُخْرِجٌ مَّا تَحْذَرُونَ", "Orang-orang munafik itu takut kalau diturunkan satu surah Al-Quran yang menerangkan kepada mereka (dan kepada ramai) akan apa yang ada dalam hati mereka (dari kekufuran). Katakanlah (wahai Muhammad): \"Ejek-ejeklah (seberapa yang kamu suka), sesungguhnya Allah akan mendedahkan apa yang kamu takut (terdedah untuk pengetahuan ramai)\"", R.raw.taubah64));
        arrayList.add(new VerseActivity("Taubah", "وَلَئِن سَأَلْتَهُمْ لَيَقُولُنَّ إِنَّمَا كُنَّا نَخُوضُ وَنَلْعَبُ ۚ قُلْ أَبِٱللَّهِ وَءَايَٰتِهِۦ وَرَسُولِهِۦ كُنتُمْ تَسْتَهْزِءُونَ", "Dan jika engkau bertanya kepada mereka (tentang ejek-ejekan itu) tentulah mereka akan menjawab: \"Sesungguhnya kami hanyalah berbual dan bermain-main\". Katakanlah: \"Patutkah nama Allah dan ayat-ayatNya serta RasulNya kamu memperolok-olok dan mengejeknya?\"", R.raw.taubah65));
        arrayList.add(new VerseActivity("Taubah", "﻿لَا تَعْتَذِرُوا۟ قَدْ كَفَرْتُم بَعْدَ إِيمَٰنِكُمْ ۚ إِن نَّعْفُ عَن طَآئِفَةٍ مِّنكُمْ نُعَذِّبْ طَآئِفَةًۢ بِأَنَّهُمْ كَانُوا۟ مُجْرِمِينَ", "Janganlah kamu berdalih (dengan alasan-alasan yang dusta), kerana sesungguhnya kamu telah kufur sesudah kamu (melahirkan) iman. Jika Kami maafkan sepuak dari kamu (kerana mereka bertaubat), maka Kami akan menyeksa puak yang lain, kerana mereka adalah orang-orang yang terus bersalah.", R.raw.taubah66));
        arrayList.add(new VerseActivity("Taubah", "ٱلْمُنَٰفِقُونَ وَٱلْمُنَٰفِقَٰتُ بَعْضُهُم مِّنۢ بَعْضٍ ۚ يَأْمُرُونَ بِٱلْمُنكَرِ وَيَنْهَوْنَ عَنِ ٱلْمَعْرُوفِ وَيَقْبِضُونَ أَيْدِيَهُمْ ۚ نَسُوا۟ ٱللَّهَ فَنَسِيَهُمْ ۗ إِنَّ ٱلْمُنَٰفِقِينَ هُمُ ٱلْفَٰسِقُونَ", "Orang-orang munafik lelaki dan perempuan, setengahnya adalah sama dengan setengahnya yang lain; mereka masing-masing menyuruh dengan perbuatan yang jahat, dan melarang dari perbuatan yang baik, dan mereka pula menggenggam tangannya (bakhil kedekut). Mereka telah melupakan (tidak menghiraukan perintah) Allah dan Allah juga melupakan (tidak menghiraukan) mereka. Sesungguhnya orang-orang munafik itu, merekalah orang-orang yang fasik.", R.raw.taubah67));
        arrayList.add(new VerseActivity("Taubah", "وَعَدَ ٱللَّهُ ٱلْمُنَٰفِقِينَ وَٱلْمُنَٰفِقَٰتِ وَٱلْكُفَّارَ نَارَ جَهَنَّمَ خَٰلِدِينَ فِيهَا ۚ هِىَ حَسْبُهُمْ ۚ وَلَعَنَهُمُ ٱللَّهُ ۖ وَلَهُمْ عَذَابٌ مُّقِيمٌ", "Allah menjanjikan orang-orang munafik lelaki dan perempuan serta orang-orang kafir dengan neraka Jahannam, mereka kekal di dalamnya. Cukuplah neraka itu menjadi balasan mereka; dan Allah melaknatkan mereka, dan bagi mereka azab seksa yang kekal.", R.raw.taubah68));
        arrayList.add(new VerseActivity("Taubah", "﻿كَٱلَّذِينَ مِن قَبْلِكُمْ كَانُوٓا۟ أَشَدَّ مِنكُمْ قُوَّةً وَأَكْثَرَ أَمْوَٰلًا وَأَوْلَٰدًا فَٱسْتَمْتَعُوا۟ بِخَلَٰقِهِمْ فَٱسْتَمْتَعْتُم بِخَلَٰقِكُمْ كَمَا ٱسْتَمْتَعَ ٱلَّذِينَ مِن قَبْلِكُم بِخَلَٰقِهِمْ وَخُضْتُمْ كَٱلَّذِى خَاضُوٓا۟ ۚ أُو۟لَٰٓئِكَ حَبِطَتْ أَعْمَٰلُهُمْ فِى ٱلدُّنْيَا وَٱلْءَاخِرَةِ ۖ وَأُو۟لَٰٓئِكَ هُمُ ٱلْخَٰسِرُونَ", "(Nasib kamu hai orang-orang munafik) adalah sama dengan nasib orang-orang sebelum kamu (yang telah dibinasakan), mereka lebih kuat serta lebih banyak harta benda dan anak pinak daripada kamu; seterusnya mereka telah bersenang-senang dengan bahagian mereka; maka kamu pula telah bersenang-senang dengan bahagian kamu sebagaimana orang-orang yang sebelum kamu itu bersenang-senang dengan bahagiannya; dan kamu pula telah memperkatakan (perkara yang salah dan dusta) sebagaimana mereka memperkatakannya. Mereka yang demikian, rosak binasalah amal-amalnya (yang baik) di dunia dan di akhirat, dan merekalah orang-orang yang rugi.", R.raw.taubah69));
        arrayList.add(new VerseActivity("Taubah", "﻿أَلَمْ يَأْتِهِمْ نَبَأُ ٱلَّذِينَ مِن قَبْلِهِمْ قَوْمِ نُوحٍ وَعَادٍ وَثَمُودَ وَقَوْمِ إِبْرَٰهِيمَ وَأَصْحَٰبِ مَدْيَنَ وَٱلْمُؤْتَفِكَٰتِ ۚ أَتَتْهُمْ رُسُلُهُم بِٱلْبَيِّنَٰتِ ۖ فَمَا كَانَ ٱللَّهُ لِيَظْلِمَهُمْ وَلَٰكِن كَانُوٓا۟ أَنفُسَهُمْ يَظْلِمُونَ", "Bukankah telah datang kepada mereka berita orang-orang yang terdahulu daripada mereka, iaitu kaum Nabi Nuh dan Aad dan Thamud dan kaum Nabi Ibrahim, dan penduduk negeri Madyan serta negeri-negeri yang telah dibinasakan? (Semuanya) telah datang kepada mereka Rasul-rasul mereka dengan membawa keterangan yang jelas nyata, (lalu mereka mendustakannya dan Tuhan pula membinasakan mereka); Allah tidak sekali-kali menganiaya mereka tetapi merekalah yang menganiaya diri sendiri.", R.raw.taubah70));

        /*ayat 71-80*/
        arrayList.add(new VerseActivity("Taubah", "﻿وَٱلْمُؤْمِنُونَ وَٱلْمُؤْمِنَٰتُ بَعْضُهُمْ أَوْلِيَآءُ بَعْضٍ ۚ يَأْمُرُونَ بِٱلْمَعْرُوفِ وَيَنْهَوْنَ عَنِ ٱلْمُنكَرِ وَيُقِيمُونَ ٱلصَّلَوٰةَ وَيُؤْتُونَ ٱلزَّكَوٰةَ وَيُطِيعُونَ ٱللَّهَ وَرَسُولَهُۥٓ ۚ أُو۟لَٰٓئِكَ سَيَرْحَمُهُمُ ٱللَّهُ ۗ إِنَّ ٱللَّهَ عَزِيزٌ حَكِيمٌ", "Dan orang-orang yang beriman, lelaki dan perempuan, setengahnya menjadi penolong bagi setengahnya yang lain; mereka menyuruh berbuat kebaikan, dan melarang daripada berbuat kejahatan; dan mereka mendirikan sembahyang dan memberi zakat, serta taat kepada Allah dan RasulNya. Mereka itu akan diberi rahmat oleh Allah; sesungguhnya Allah Maha Kuasa, lagi Maha Bijaksana.", R.raw.taubah71));
        arrayList.add(new VerseActivity("Taubah", "وَعَدَ ٱللَّهُ ٱلْمُؤْمِنِينَ وَٱلْمُؤْمِنَٰتِ جَنَّٰتٍ تَجْرِى مِن تَحْتِهَا ٱلْأَنْهَٰرُ خَٰلِدِينَ فِيهَا وَمَسَٰكِنَ طَيِّبَةً فِى جَنَّٰتِ عَدْنٍ ۚ وَرِضْوَٰنٌ مِّنَ ٱللَّهِ أَكْبَرُ ۚ ذَٰلِكَ هُوَ ٱلْفَوْزُ ٱلْعَظِيمُ", "Allah menjanjikan orang-orang yang beriman, lelaki dan perempuan, (akan beroleh) Syurga-syurga yang mengalir di bawahnya beberapa sungai; mereka kekal di dalamnya dan beroleh tempat-tempat yang baik di dalam \"Syurga Adn\" serta keredaan dari Allah yang lebih besar kemuliaannya; (balasan) yang demikian itulah kejayaan yang besar.", R.raw.taubah72));
        arrayList.add(new VerseActivity("Taubah", "يَٰٓأَيُّهَا ٱلنَّبِىُّ جَٰهِدِ ٱلْكُفَّارَ وَٱلْمُنَٰفِقِينَ وَٱغْلُظْ عَلَيْهِمْ ۚ وَمَأْوَىٰهُمْ جَهَنَّمُ ۖ وَبِئْسَ ٱلْمَصِيرُ", "Wahai Nabi, berjihadlah menentang orang-orang kafir dan orang-orang munafik, dan bertindak keras terhadap mereka. Dan (sebenarnya) tempat mereka ialah neraka Jahannam, dan itulah seburuk-buruk tempat kembali.", R.raw.taubah73));
        arrayList.add(new VerseActivity("Taubah", "يَحْلِفُونَ بِٱللَّهِ مَا قَالُوا۟ وَلَقَدْ قَالُوا۟ كَلِمَةَ ٱلْكُفْرِ وَكَفَرُوا۟ بَعْدَ إِسْلَٰمِهِمْ وَهَمُّوا۟ بِمَا لَمْ يَنَالُوا۟ ۚ وَمَا نَقَمُوٓا۟ إِلَّآ أَنْ أَغْنَىٰهُمُ ٱللَّهُ وَرَسُولُهُۥ مِن فَضْلِهِۦ ۚ فَإِن يَتُوبُوا۟ يَكُ خَيْرًا لَّهُمْ ۖ وَإِن يَتَوَلَّوْا۟ يُعَذِّبْهُمُ ٱللَّهُ عَذَابًا أَلِيمًا فِى ٱلدُّنْيَا وَٱلْءَاخِرَةِ ۚ وَمَا لَهُمْ فِى ٱلْأَرْضِ مِن وَلِىٍّ وَلَا نَصِيرٍ", "Mereka bersumpah dengan nama Allah, bahawa mereka tidak mengatakan (sesuatu yang buruk terhadapmu), padahal sesungguhnya mereka telah mengatakan perkataan kufur, dan mereka pula menjadi kafir sesudah melahirkan Islam, serta mereka berazam untuk melakukan apa yang mereka tidak akan dapat mencapainya (iaitu membunuhmu). Dan tidaklah mereka mencaci dan mencela (Islam) melainkan setelah Allah dan RasulNya memberi kesenangan kepada mereka dari limpah kurniaNya. Oleh itu, jika mereka bertaubat, mereka akan beroleh kebaikan; dan jika mereka berpaling (ingkar), Allah akan menyeksa mereka dengan azab seksa yang tidak terperi sakitnya di dunia dan di akhirat; dan mereka tidak akan mendapat sesiapa pun di bumi ini, yang akan menjadi pelindung dan juga yang menjadi penolong.", R.raw.taubah74));
        arrayList.add(new VerseActivity("Taubah", "۞ وَمِنْهُم مَّنْ عَٰهَدَ ٱللَّهَ لَئِنْ ءَاتَىٰنَا مِن فَضْلِهِۦ لَنَصَّدَّقَنَّ وَلَنَكُونَنَّ مِنَ ٱلصَّٰلِحِينَ", "Dan di antara mereka ada yang membuat janji dengan Allah dengan berkata: \"Sesungguhnya jika Allah memberi kepada kami dari limpah kurniaNya, tentulah kami akan bersedekah, dan tentulah kami akan menjadi dari orang-orang yang soleh\"", R.raw.taubah75));
        arrayList.add(new VerseActivity("Taubah", "فَلَمَّآ ءَاتَىٰهُم مِّن فَضْلِهِۦ بَخِلُوا۟ بِهِۦ وَتَوَلَّوا۟ وَّهُم مُّعْرِضُونَ", "Kemudian setelah Allah memberi kepada mereka dari limpah kurniaNya, mereka bakhil dengan pemberian Allah itu, serta mereka membelakangkan janjinya; dan sememangnya mereka orang-orang yang sentiasa membelakangkan (kebajikan).", R.raw.taubah76));
        arrayList.add(new VerseActivity("Taubah", "﻿فَأَعْقَبَهُمْ نِفَاقًا فِى قُلُوبِهِمْ إِلَىٰ يَوْمِ يَلْقَوْنَهُۥ بِمَآ أَخْلَفُوا۟ ٱللَّهَ مَا وَعَدُوهُ وَبِمَا كَانُوا۟ يَكْذِبُونَ", "Akibatnya Allah menimbulkan perasaan munafik dalam hati mereka (berkekalan) hingga ke masa mereka menemui Allah, kerana mereka telah memungkiri apa yang mereka janjikan kepada Allah dan juga kerana mereka sentiasa berdusta.", R.raw.taubah77));
        arrayList.add(new VerseActivity("Taubah", "﻿أَلَمْ يَعْلَمُوٓا۟ أَنَّ ٱللَّهَ يَعْلَمُ سِرَّهُمْ وَنَجْوَىٰهُمْ وَأَنَّ ٱللَّهَ عَلَّٰمُ ٱلْغُيُوبِ", "Tidakkah mereka mengetahui bahawa Allah sentiasa mengetahui apa yang mereka rahsiakan serta apa yang mereka bisikkan, dan bahawasanya Allah Maha Mengetahui akan perkara-perkara yang ghaib?", R.raw.taubah78));
        arrayList.add(new VerseActivity("Taubah", "﻿ٱلَّذِينَ يَلْمِزُونَ ٱلْمُطَّوِّعِينَ مِنَ ٱلْمُؤْمِنِينَ فِى ٱلصَّدَقَٰتِ وَٱلَّذِينَ لَا يَجِدُونَ إِلَّا جُهْدَهُمْ فَيَسْخَرُونَ مِنْهُمْ ۙ سَخِرَ ٱللَّهُ مِنْهُمْ وَلَهُمْ عَذَابٌ أَلِيمٌ", "Orang-orang (munafik) yang mencela sebahagian dari orang-orang yang beriman mengenai sedekah-sedekah yang mereka berikan dengan sukarela, dan (mencela) orang-orang yang tidak dapat (mengadakan apa-apa untuk disedekahkan) kecuali sedikit sekadar kemampuannya, serta mereka mengejek-ejeknya, - Allah akan membalas ejek-ejekan mereka, dan bagi mereka (disediakan) azab seksa yang tidak terperi sakitnya.", R.raw.taubah79));
        arrayList.add(new VerseActivity("Taubah", "﻿ٱسْتَغْفِرْ لَهُمْ أَوْ لَا تَسْتَغْفِرْ لَهُمْ إِن تَسْتَغْفِرْ لَهُمْ سَبْعِينَ مَرَّةً فَلَن يَغْفِرَ ٱللَّهُ لَهُمْ ۚ ذَٰلِكَ بِأَنَّهُمْ كَفَرُوا۟ بِٱللَّهِ وَرَسُولِهِۦ ۗ وَٱللَّهُ لَا يَهْدِى ٱلْقَوْمَ ٱلْفَٰسِقِينَ", "(Orang-orang manufik itu) sama sahaja engkau meminta ampun untuk mereka atau engkau tidak meminta ampun bagi mereka. Jika engkau (wahai Muhammad) meminta ampun bagi mereka tujuh puluh kali (sekalipun) maka Allah tidak sekali-kali mengampunkan mereka; yang demikian itu, kerana mereka telah kufur kepada Allah dan RasulNya; dan Allah tidak akan memberi hidayah petunjuk kepada kaum yang fasik.", R.raw.taubah80));

        /*ayat 81-90*/
        arrayList.add(new VerseActivity("Taubah", "﻿فَرِحَ ٱلْمُخَلَّفُونَ بِمَقْعَدِهِمْ خِلَٰفَ رَسُولِ ٱللَّهِ وَكَرِهُوٓا۟ أَن يُجَٰهِدُوا۟ بِأَمْوَٰلِهِمْ وَأَنفُسِهِمْ فِى سَبِيلِ ٱللَّهِ وَقَالُوا۟ لَا تَنفِرُوا۟ فِى ٱلْحَرِّ ۗ قُلْ نَارُ جَهَنَّمَ أَشَدُّ حَرًّا ۚ لَّوْ كَانُوا۟ يَفْقَهُونَ", "Orang-orang (munafik) yang ditinggalkan (tidak turut berperang) itu, bersukacita disebabkan mereka tinggal di belakang Rasulullah (di Madinah); dan mereka (sememangnya) tidak suka berjihad dengan harta benda dan jiwa mereka pada jalan Allah (dengan sebab kufurnya), dan mereka pula (menghasut dengan) berkata: \"Janganlah kamu keluar beramai-ramai (untuk berperang) pada musim panas ini\". Katakanlah (wahai Muhammad): \"Api neraka Jahannam lebih panas membakar\", kalaulah mereka itu orang-orang yang memahami.", R.raw.taubah81));
        arrayList.add(new VerseActivity("Taubah", "﻿فَلْيَضْحَكُوا۟ قَلِيلًا وَلْيَبْكُوا۟ كَثِيرًا جَزَآءًۢ بِمَا كَانُوا۟ يَكْسِبُونَ", "Oleh itu bolehlah mereka ketawa sedikit (di dunia ini) dan mereka akan menangis banyak (di akhirat kelak), sebagai balasan bagi apa yang mereka telah usahakan.", R.raw.taubah82));
        arrayList.add(new VerseActivity("Taubah", "فَإِن رَّجَعَكَ ٱللَّهُ إِلَىٰ طَآئِفَةٍ مِّنْهُمْ فَٱسْتَـْٔذَنُوكَ لِلْخُرُوجِ فَقُل لَّن تَخْرُجُوا۟ مَعِىَ أَبَدًا وَلَن تُقَٰتِلُوا۟ مَعِىَ عَدُوًّا ۖ إِنَّكُمْ رَضِيتُم بِٱلْقُعُودِ أَوَّلَ مَرَّةٍ فَٱقْعُدُوا۟ مَعَ ٱلْخَٰلِفِينَ", "Maka jika Allah mengembalikan engkau kepada segolongan dari mereka (orang-orang yang munafik itu di Madinah), kemudian mereka meminta izin kepadamu untuk keluar (turut berperang), maka katakanlah: \"Kamu tidak sekali-kali akan keluar bersama-samaku selama-lamanya, dan kamu tidak sekali-kali akan memerangi musuh bersama-samaku; sesungguhnya kamu telah bersetuju tinggal pada kali yang pertama, oleh itu duduklah kamu bersama-sama orang-orang yang tinggal\".", R.raw.taubah83));
        arrayList.add(new VerseActivity("Taubah", "وَلَا تُصَلِّ عَلَىٰٓ أَحَدٍ مِّنْهُم مَّاتَ أَبَدًا وَلَا تَقُمْ عَلَىٰ قَبْرِهِۦٓ ۖ إِنَّهُمْ كَفَرُوا۟ بِٱللَّهِ وَرَسُولِهِۦ وَمَاتُوا۟ وَهُمْ فَٰسِقُونَ", "Dan janganlah engkau sembahyangkan seorang pun yang mati dari orang-orang munafik itu selama-lamanya, dan janganlah engkau berada di (tepi) kuburnya, kerana sesungguhnya mereka telah kufur kepada Allah dan RasulNya, dan mereka mati sedang mereka dalam keadaan fasik (derhaka).", R.raw.taubah84));
        arrayList.add(new VerseActivity("Taubah", "وَلَا تُعْجِبْكَ أَمْوَٰلُهُمْ وَأَوْلَٰدُهُمْ ۚ إِنَّمَا يُرِيدُ ٱللَّهُ أَن يُعَذِّبَهُم بِهَا فِى ٱلدُّنْيَا وَتَزْهَقَ أَنفُسُهُمْ وَهُمْ كَٰفِرُونَ", "Dan janganlah engkau tertarik hati kepada harta benda dan anak-anak mereka, (kerana) sesungguhnya Allah hanya hendak menyeksa mereka dengannya di dunia, dan hendak menjadikan nyawa mereka tercabut sedang mereka dalam keadaan kafir (untuk mendapat azab akhirat pula).", R.raw.taubah85));
        arrayList.add(new VerseActivity("Taubah", "﻿وَإِذَآ أُنزِلَتْ سُورَةٌ أَنْ ءَامِنُوا۟ بِٱللَّهِ وَجَٰهِدُوا۟ مَعَ رَسُولِهِ ٱسْتَـْٔذَنَكَ أُو۟لُوا۟ ٱلطَّوْلِ مِنْهُمْ وَقَالُوا۟ ذَرْنَا نَكُن مَّعَ ٱلْقَٰعِدِينَ", "Dan apabila diturunkan satu surah Al-Quran (yang menyuruh mereka): \"Berimanlah kamu kepada Allah, dan berjihadlah bersama-sama dengan RasulNya\", nescaya orang-orang yang kaya di antara mereka meminta izin kepadamu dengan berkata: \"Biarkanlah kami tinggal bersama-sama orang-orang yang tinggal (tidak turut berperang)\".", R.raw.taubah86));
        arrayList.add(new VerseActivity("Taubah", "﻿رَضُوا۟ بِأَن يَكُونُوا۟ مَعَ ٱلْخَوَالِفِ وَطُبِعَ عَلَىٰ قُلُوبِهِمْ فَهُمْ لَا يَفْقَهُونَ", "Mereka suka tinggal bersama-sama orang-orang yang ditinggalkan (kerana uzur), dan (dengan sebab itu) hati mereka dimeteraikan atasnya, sehingga mereka tidak dapat memahami sesuatu.", R.raw.taubah87));
        arrayList.add(new VerseActivity("Taubah", "لَٰكِنِ ٱلرَّسُولُ وَٱلَّذِينَ ءَامَنُوا۟ مَعَهُۥ جَٰهَدُوا۟ بِأَمْوَٰلِهِمْ وَأَنفُسِهِمْ ۚ وَأُو۟لَٰٓئِكَ لَهُمُ ٱلْخَيْرَٰتُ ۖ وَأُو۟لَٰٓئِكَ هُمُ ٱلْمُفْلِحُونَ", "(Mereka tetap tinggal) tetapi Rasulullah dan orang-orang yang beriman bersamanya, berjihad dengan harta benda dan jiwa mereka; dan mereka itulah orang-orang yang mendapat kebaikan, dan mereka itulah juga yang berjaya.", R.raw.taubah88));
        arrayList.add(new VerseActivity("Taubah", "﻿أَعَدَّ ٱللَّهُ لَهُمْ جَنَّٰتٍ تَجْرِى مِن تَحْتِهَا ٱلْأَنْهَٰرُ خَٰلِدِينَ فِيهَا ۚ ذَٰلِكَ ٱلْفَوْزُ ٱلْعَظِيمُ", "Allah telah menyediakan untuk mereka Syurga-syurga yang mengalir di bawahnya beberapa sungai, mereka kekal di dalamnya; yang demikian itulah kemenangan yang besar.", R.raw.taubah89));
        arrayList.add(new VerseActivity("Taubah", "وَجَآءَ ٱلْمُعَذِّرُونَ مِنَ ٱلْأَعْرَابِ لِيُؤْذَنَ لَهُمْ وَقَعَدَ ٱلَّذِينَ كَذَبُوا۟ ٱللَّهَ وَرَسُولَهُۥ ۚ سَيُصِيبُ ٱلَّذِينَ كَفَرُوا۟ مِنْهُمْ عَذَابٌ أَلِيمٌ", "Dan datanglah pula orang-orang yang menyatakan uzurnya dari orang-orang \"A'raab\", memohon supaya mereka diizinkan (tidak turut berperang), sedang orang-orang (munafik di antara mereka) yang mendustakan Allah dan RasulNya, duduk (mendiamkan diri). (Oleh itu) orang-orang yang kafir di antara mereka, akan dikenakan azab seksa yang tidak terperi sakitnya.", R.raw.taubah90));

        /*ayat 91-98*/
        arrayList.add(new VerseActivity("Taubah", "لَّيْسَ عَلَى ٱلضُّعَفَآءِ وَلَا عَلَى ٱلْمَرْضَىٰ وَلَا عَلَى ٱلَّذِينَ لَا يَجِدُونَ مَا يُنفِقُونَ حَرَجٌ إِذَا نَصَحُوا۟ لِلَّهِ وَرَسُولِهِۦ ۚ مَا عَلَى ٱلْمُحْسِنِينَ مِن سَبِيلٍ ۚ وَٱللَّهُ غَفُورٌ رَّحِيمٌ", "Orang-orang yang lemah dan orang-orang yang sakit, dan juga orang-orang yang tidak mempunyai sesuatu yang akan dibelanjakan, tidaklah menanggung dosa (kerana tidak turut berperang) apabila mereka berlaku ikhlas kepada Allah dan RasulNya. Tidak ada jalan sedikitpun bagi menyalahkan orang-orang yang berusaha memperbaiki amalannya; dan Allah Maha Pengampun, lagi Maha Mengasihani.", R.raw.taubah91));
        arrayList.add(new VerseActivity("Taubah", "﻿وَلَا عَلَى ٱلَّذِينَ إِذَا مَآ أَتَوْكَ لِتَحْمِلَهُمْ قُلْتَ لَآ أَجِدُ مَآ أَحْمِلُكُمْ عَلَيْهِ تَوَلَّوا۟ وَّأَعْيُنُهُمْ تَفِيضُ مِنَ ٱلدَّمْعِ حَزَنًا أَلَّا يَجِدُوا۟ مَا يُنفِقُونَ", "Dan tidak juga berdosa orang-orang yang ketika mereka datang kepadamu (memohon) supaya engkau memberi kenderaan kepada mereka, engkau berkata: \"Tidak ada padaku kenderaan yang hendak kuberikan untuk membawa kamu\", mereka kembali sedang mata mereka mengalirkan airmata yang bercucuran, kerana sedih bahawa mereka tidak mempunyai sesuatupun yang hendak mereka belanjakan (untuk pergi berjihad pada jalan Allah).", R.raw.taubah92));
        arrayList.add(new VerseActivity("Taubah", "۞ إِنَّمَا ٱلسَّبِيلُ عَلَى ٱلَّذِينَ يَسْتَـْٔذِنُونَكَ وَهُمْ أَغْنِيَآءُ ۚ رَضُوا۟ بِأَن يَكُونُوا۟ مَعَ ٱلْخَوَالِفِ وَطَبَعَ ٱللَّهُ عَلَىٰ قُلُوبِهِمْ فَهُمْ لَا يَعْلَمُونَ", "Sesungguhnya jalan (untuk menyalahkan dan mengenakan seksa) hanyalah terhadap orang-orang yang meminta izin kepadamu sedang mereka kaya dan mampu. Mereka suka tinggal bersama-sama orang yang ditinggalkan (kerana uzur) dan (dengan sebab itu) Allah meteraikan atas hati mereka, sehingga mereka tidak dapat mengetahui (perkara yang baik).", R.raw.taubah93));
        arrayList.add(new VerseActivity("Taubah", "﻿يَعْتَذِرُونَ إِلَيْكُمْ إِذَا رَجَعْتُمْ إِلَيْهِمْ ۚ قُل لَّا تَعْتَذِرُوا۟ لَن نُّؤْمِنَ لَكُمْ قَدْ نَبَّأَنَا ٱللَّهُ مِنْ أَخْبَارِكُمْ ۚ وَسَيَرَى ٱللَّهُ عَمَلَكُمْ وَرَسُولُهُۥ ثُمَّ تُرَدُّونَ إِلَىٰ عَٰلِمِ ٱلْغَيْبِ وَٱلشَّهَٰدَةِ فَيُنَبِّئُكُم بِمَا كُنتُمْ تَعْمَلُونَ", "Mereka akan menyatakan uzur kepada kamu, apabila kamu kembali kepada mereka (dari medan perang). Katakanlah (wahai Muhammad): \"Janganlah kamu menyatakan uzur lagi, kami tidak sekali-kali akan percaya kepada kamu. Kerana sesungguhnya Allah telah menerangkan kepada kami akan berita-berita perihal kamu; dan Allah serta RasulNya akan melihat amal kamu (sama ada kamu kembali beriman atau tetap kufur); kemudian kamu akan dikembalikan kepada (Allah) Yang Mengetahui perkara-perkara yang ghaib dan yang nyata (untuk menerima balasan), lalu Ia menyatakan kepada kamu apa yang kamu telah kerjakan\".", R.raw.taubah94));
        arrayList.add(new VerseActivity("Taubah", "﻿سَيَحْلِفُونَ بِٱللَّهِ لَكُمْ إِذَا ٱنقَلَبْتُمْ إِلَيْهِمْ لِتُعْرِضُوا۟ عَنْهُمْ ۖ فَأَعْرِضُوا۟ عَنْهُمْ ۖ إِنَّهُمْ رِجْسٌ ۖ وَمَأْوَىٰهُمْ جَهَنَّمُ جَزَآءًۢ بِمَا كَانُوا۟ يَكْسِبُونَ", "Mereka akan bersumpah dengan nama Allah kepada kamu apabila kamu kembali kepada mereka (dari medan perang), supaya kamu berpaling dari mereka (tidak menempelak mereka); oleh itu berpalinglah dari mereka kerana sesungguhnya mereka itu kotor (disebabkan mereka telah sebati dengan kufur); dan tempat kembali mereka pula ialah neraka Jahannam, sebagai balasan bagi apa yang mereka telah usahakan.", R.raw.taubah95));
        arrayList.add(new VerseActivity("Taubah", "يَحْلِفُونَ لَكُمْ لِتَرْضَوْا۟ عَنْهُمْ ۖ فَإِن تَرْضَوْا۟ عَنْهُمْ فَإِنَّ ٱللَّهَ لَا يَرْضَىٰ عَنِ ٱلْقَوْمِ ٱلْفَٰسِقِينَ", "Mereka bersumpah kepada kamu supaya kamu reda akan mereka; oleh itu jika kamu reda akan mereka, maka sesungguhnya Allah tidak reda akan kaum yang fasik.", R.raw.taubah96));
        arrayList.add(new VerseActivity("Taubah", "ٱلْأَعْرَابُ أَشَدُّ كُفْرًا وَنِفَاقًا وَأَجْدَرُ أَلَّا يَعْلَمُوا۟ حُدُودَ مَآ أَنزَلَ ٱللَّهُ عَلَىٰ رَسُولِهِۦ ۗ وَٱللَّهُ عَلِيمٌ حَكِيمٌ", "Orang-orang A'raab lebih keras kufurnya dan sikap munafiknya, dan sangatlah patut mereka tidak mengetahui batas-batas (dan hukum-hukum Syarak) yang diturunkan oleh Allah kepada RasulNya. Dan (ingatlah) Allah Maha Mengetahui, lagi Maha Bijaksana.", R.raw.taubah97));
        arrayList.add(new VerseActivity("Taubah", "﻿وَمِنَ ٱلْأَعْرَابِ مَن يَتَّخِذُ مَا يُنفِقُ مَغْرَمًا وَيَتَرَبَّصُ بِكُمُ ٱلدَّوَآئِرَ ۚ عَلَيْهِمْ دَآئِرَةُ ٱلسَّوْءِ ۗ وَٱللَّهُ سَمِيعٌ عَلِيمٌ", "Dan sebahagian dari orang-orang A'raab (yang munafik) itu memandang apa yang mereka belanjakan (dermakan pada jalan Allah) sebagai satu bayaran yang memberatkan, sambil menunggu peredaran zaman (yang membawa bala bencana) menimpa kamu; atas merekalah (tertimpanya bala bencana yang dibawa oleh) peredaran zaman yang buruk itu. Dan (ingatlah), Allah Maha Mendengar lagi Maha Mengetahui.", R.raw.taubah98));
        arrayList.add(new VerseActivity("Taubah", "وَمِنَ ٱلْأَعْرَابِ مَن يُؤْمِنُ بِٱللَّهِ وَٱلْيَوْمِ ٱلْءَاخِرِ وَيَتَّخِذُ مَا يُنفِقُ قُرُبَٰتٍ عِندَ ٱللَّهِ وَصَلَوَٰتِ ٱلرَّسُولِ ۚ أَلَآ إِنَّهَا قُرْبَةٌ لَّهُمْ ۚ سَيُدْخِلُهُمُ ٱللَّهُ فِى رَحْمَتِهِۦٓ ۗ إِنَّ ٱللَّهَ غَفُورٌ رَّحِيمٌ", "Dan sebahagian dari orang-orang A'raab itu ada yang beriman kepada Allah dan hari akhirat, dan memandang apa yang mereka dermakan (pada jalan Allah itu) sebagai amal-amal bakti (yang mendampingkan) di sisi Allah dan sebagai (satu jalan untuk mendapat) doa dari Rasulullah (yang membawa rahmat kepada mereka) Ketahuilah, sesungguhnya apa yang mereka dermakan itu adalah menjadi amal bakti bagi mereka (yang mendampingkan mereka kepada Allah); Allah akan masukkan mereka ke dalam rahmatNya; sesungguhnya Allah Maha Pengampun, lagi Maha Mengasihani.", R.raw.taubah99));
        arrayList.add(new VerseActivity("Taubah", "﻿وَٱلسَّٰبِقُونَ ٱلْأَوَّلُونَ مِنَ ٱلْمُهَٰجِرِينَ وَٱلْأَنصَارِ وَٱلَّذِينَ ٱتَّبَعُوهُم بِإِحْسَٰنٍ رَّضِىَ ٱللَّهُ عَنْهُمْ وَرَضُوا۟ عَنْهُ وَأَعَدَّ لَهُمْ جَنَّٰتٍ تَجْرِى تَحْتَهَا ٱلْأَنْهَٰرُ خَٰلِدِينَ فِيهَآ أَبَدًا ۚ ذَٰلِكَ ٱلْفَوْزُ ٱلْعَظِيمُ", "Dan orang-orang yang terdahulu - yang mula-mula (berhijrah dan memberi bantuan) dari orang-orang \"Muhajirin\" dan \"Ansar\", dan orang-orang yang menurut (jejak langkah) mereka dengan kebaikan (iman dan taat), Allah reda akan mereka dan mereka pula reda akan Dia, serta Ia menyediakan untuk mereka Syurga-syurga yang mengalir di bawahnya beberapa sungai, mereka kekal di dalamnya selama-lamanya; itulah kemenangan yang besar.", R.raw.taubah100));

        /*ayat 101-110*/
        arrayList.add(new VerseActivity("Taubah", "وَمِمَّنْ حَوْلَكُم مِّنَ ٱلْأَعْرَابِ مُنَٰفِقُونَ ۖ وَمِنْ أَهْلِ ٱلْمَدِينَةِ ۖ مَرَدُوا۟ عَلَى ٱلنِّفَاقِ لَا تَعْلَمُهُمْ ۖ نَحْنُ نَعْلَمُهُمْ ۚ سَنُعَذِّبُهُم مَّرَّتَيْنِ ثُمَّ يُرَدُّونَ إِلَىٰ عَذَابٍ عَظِيمٍ", "Dan di antara orang-orang yang di sekeliling kamu dari orang-orang \"A'raab\" ada yang bersifat munafik dan (demikian juga) sebahagian dari penduduk Madinah; mereka telah berkeras dengan sifat munafik; engkau tidak mengetahui mereka (bahkan) Kamilah yang mengetahui mereka. Kami akan azabkan mereka berulang-ulang, kemudian mereka dikembalikan kepada azab yang besar.", R.raw.taubah101));
        arrayList.add(new VerseActivity("Taubah", "﻿وَءَاخَرُونَ ٱعْتَرَفُوا۟ بِذُنُوبِهِمْ خَلَطُوا۟ عَمَلًا صَٰلِحًا وَءَاخَرَ سَيِّئًا عَسَى ٱللَّهُ أَن يَتُوبَ عَلَيْهِمْ ۚ إِنَّ ٱللَّهَ غَفُورٌ رَّحِيمٌ", "Dan (sebahagian) yang lain mengakui dosa-dosa mereka. Mereka telah mencampur adukkan amal yang baik dengan amal yang lain, yang buruk. Mudah-mudahan Allah akan menerima taubat mereka; sesungguhnya Allah Maha Pengampun, lagi Maha Mengasihani.", R.raw.taubah102));
        arrayList.add(new VerseActivity("Taubah", "﻿خُذْ مِنْ أَمْوَٰلِهِمْ صَدَقَةً تُطَهِّرُهُمْ وَتُزَكِّيهِم بِهَا وَصَلِّ عَلَيْهِمْ ۖ إِنَّ صَلَوٰتَكَ سَكَنٌ لَّهُمْ ۗ وَٱللَّهُ سَمِيعٌ عَلِيمٌ", "Ambilah (sebahagian) dari harta mereka menjadi sedekah (zakat), supaya dengannya engkau membersihkan mereka (dari dosa) dan mensucikan mereka (dari akhlak yang buruk); dan doakanlah untuk mereka, kerana sesungguhnya doamu itu menjadi ketenteraman bagi mereka. Dan (ingatlah) Allah Maha Mendengar, lagi Maha Mengetahui.", R.raw.taubah103));
        arrayList.add(new VerseActivity("Taubah", "أَلَمْ يَعْلَمُوٓا۟ أَنَّ ٱللَّهَ هُوَ يَقْبَلُ ٱلتَّوْبَةَ عَنْ عِبَادِهِۦ وَيَأْخُذُ ٱلصَّدَقَٰتِ وَأَنَّ ٱللَّهَ هُوَ ٱلتَّوَّابُ ٱلرَّحِيمُ", "Tidakkah mereka mengetahui bahawa Allah Dia lah yang menerima taubat dari hamba-hambaNya, dan juga menerima sedekah-sedekah (dan zakat serta membalasnya), dan bahawa sesungguhnya Allah Dia lah Penerima taubat, lagi Maha Mengasihani?", R.raw.taubah104));
        arrayList.add(new VerseActivity("Taubah", "﻿وَقُلِ ٱعْمَلُوا۟ فَسَيَرَى ٱللَّهُ عَمَلَكُمْ وَرَسُولُهُۥ وَٱلْمُؤْمِنُونَ ۖ وَسَتُرَدُّونَ إِلَىٰ عَٰلِمِ ٱلْغَيْبِ وَٱلشَّهَٰدَةِ فَيُنَبِّئُكُم بِمَا كُنتُمْ تَعْمَلُونَ", "Dan katakanlah (wahai Muhammad): Beramalah kamu (akan segala yang diperintahkan), maka Allah dan RasulNya serta orang-orang yang beriman akan melihat apa yang kamu kerjakan; dan kamu akan dikembalikan kepada (Allah) Yang Mengetahui perkara-perkara yang ghaib dan yang nyata, kemudian Ia menerangkan kepada kamu apa yang kamu telah kerjakan\".", R.raw.taubah105));
        arrayList.add(new VerseActivity("Taubah", "وَءَاخَرُونَ مُرْجَوْنَ لِأَمْرِ ٱللَّهِ إِمَّا يُعَذِّبُهُمْ وَإِمَّا يَتُوبُ عَلَيْهِمْ ۗ وَٱللَّهُ عَلِيمٌ حَكِيمٌ", "Dan segolongan yang lain (dari orang-orang yang tidak turut berperang); ditempohkan keputusan mengenai mereka kerana menunggu perintah Allah; sama ada dia mengazabkan mereka ataupun Ia menerima taubat mereka. Dan (ingatlah) Allah Maha Mengetahui, lagi Maha Bijaksana.", R.raw.taubah106));
        arrayList.add(new VerseActivity("Taubah", "وَٱلَّذِينَ ٱتَّخَذُوا۟ مَسْجِدًا ضِرَارًا وَكُفْرًا وَتَفْرِيقًۢا بَيْنَ ٱلْمُؤْمِنِينَ وَإِرْصَادًا لِّمَنْ حَارَبَ ٱللَّهَ وَرَسُولَهُۥ مِن قَبْلُ ۚ وَلَيَحْلِفُنَّ إِنْ أَرَدْنَآ إِلَّا ٱلْحُسْنَىٰ ۖ وَٱللَّهُ يَشْهَدُ إِنَّهُمْ لَكَٰذِبُونَ", "Dan (di antara orang-orang munafik juga ialah) orang-orang yang membina masjid dengan tujuan membahayakan (keselamatan orang-orang Islam), dan (menguatkan) keingkaran (mereka sendiri) serta memecah-belahkan perpaduan orang-orang yang beriman, dan juga untuk (dijadikan tempat) intipan bagi orang yang telah memerangi Allah dan RasulNya sebelum itu. Dan (apabila tujuan mereka yang buruk itu ketara), mereka akan bersumpah dengan berkata:\" Tidaklah yang kami kehendaki (dengan mendirikan masjid ini) melainkan untuk kebaikan semata-mata \". Padahal Allah menyaksikan, bahawa sesungguhnya mereka adalah berdusta.", R.raw.taubah107));
        arrayList.add(new VerseActivity("Taubah", "﻿لَا تَقُمْ فِيهِ أَبَدًا ۚ لَّمَسْجِدٌ أُسِّسَ عَلَى ٱلتَّقْوَىٰ مِنْ أَوَّلِ يَوْمٍ أَحَقُّ أَن تَقُومَ فِيهِ ۚ فِيهِ رِجَالٌ يُحِبُّونَ أَن يَتَطَهَّرُوا۟ ۚ وَٱللَّهُ يُحِبُّ ٱلْمُطَّهِّرِينَ", "Jangan engkau sembahyang di masjid itu selama-lamanya, kerana sesungguhnya masjid (Qubaa' yang engkau bina wahai Muhammad), yang telah didirikan di atas dasar taqwa dari mula (wujudnya), sudah sepatutnya engkau sembahyang padanya. Di dalam masjid itu ada orang-orang lelaki yang suka (mengambil berat) membersihkan (mensucikan) dirinya; dan Allah Mengasihi orang-orang yang membersihkan diri mereka (zahir dan batin).", R.raw.taubah108));
        arrayList.add(new VerseActivity("Taubah", "﻿أَفَمَنْ أَسَّسَ بُنْيَٰنَهُۥ عَلَىٰ تَقْوَىٰ مِنَ ٱللَّهِ وَرِضْوَٰنٍ خَيْرٌ أَم مَّنْ أَسَّسَ بُنْيَٰنَهُۥ عَلَىٰ شَفَا جُرُفٍ هَارٍ فَٱنْهَارَ بِهِۦ فِى نَارِ جَهَنَّمَ ۗ وَٱللَّهُ لَا يَهْدِى ٱلْقَوْمَ ٱلظَّٰلِمِينَ", "Maka adakah orang yang membangunkan masjid yang didirikannya di atas dasar taqwa kepada Allah dan (untuk mencari) keredaan Allah itu lebih baik, ataukah orang yang membangunkan masjid yang didirikannya di tepi jurang yang (hampir) runtuh, lalu runtuhlah ia dengan yang membangunkannya ke dalam api neraka? Dan (ingatlah) Allah tidak akan memberi hidayah petunjuk kepada orang-orang yang zalim.", R.raw.taubah109));
        arrayList.add(new VerseActivity("Taubah", "﻿لَا يَزَالُ بُنْيَٰنُهُمُ ٱلَّذِى بَنَوْا۟ رِيبَةً فِى قُلُوبِهِمْ إِلَّآ أَن تَقَطَّعَ قُلُوبُهُمْ ۗ وَٱللَّهُ عَلِيمٌ حَكِيمٌ", "(Keruntuhan masjid) yang dibina oleh mereka yang munafik itu sentiasa menjadi penyakit syak dan keluh-kesah (lebih daripada yang sedia ada) dalam hati mereka, (dan tidak akan habis) kecuali (apabila) hati mereka hancur-luluh (dalam tanah). Dan (ingatlah) Allah Maha Mengetahui, lagi Maha Bijaksana.", R.raw.taubah110));

        /*ayat 111-120*/
        arrayList.add(new VerseActivity("Taubah", "﻿۞ إِنَّ ٱللَّهَ ٱشْتَرَىٰ مِنَ ٱلْمُؤْمِنِينَ أَنفُسَهُمْ وَأَمْوَٰلَهُم بِأَنَّ لَهُمُ ٱلْجَنَّةَ ۚ يُقَٰتِلُونَ فِى سَبِيلِ ٱللَّهِ فَيَقْتُلُونَ وَيُقْتَلُونَ ۖ وَعْدًا عَلَيْهِ حَقًّا فِى ٱلتَّوْرَىٰةِ وَٱلْإِنجِيلِ وَٱلْقُرْءَانِ ۚ وَمَنْ أَوْفَىٰ بِعَهْدِهِۦ مِنَ ٱللَّهِ ۚ فَٱسْتَبْشِرُوا۟ بِبَيْعِكُمُ ٱلَّذِى بَايَعْتُم بِهِۦ ۚ وَذَٰلِكَ هُوَ ٱلْفَوْزُ ٱلْعَظِيمُ", "Sesungguhnya Allah telah membeli dari orang-orang yang beriman akan jiwa mereka dan harta benda mereka dengan (balasan) bahawa mereka akan beroleh Syurga, (disebabkan) mereka berjuang pada jalan Allah maka (di antara) mereka ada yang membunuh dan terbunuh. (Balasan Syurga yang demikian ialah) sebagai janji yang benar yang ditetapkan oleh Allah di dalam (Kitab-kitab) Taurat dan Injil serta Al-Quran; dan siapakah lagi yang lebih menyempurnakan janjinya daripada Allah? Oleh itu, bergembiralah dengan jualan yang kamu jalankan jual-belinya itu, dan (ketahuilah bahawa) jual-beli (yang seperti itu) ialah kemenangan yang besar.", R.raw.taubah111));
        arrayList.add(new VerseActivity("Taubah", "ٱلتَّٰٓئِبُونَ ٱلْعَٰبِدُونَ ٱلْحَٰمِدُونَ ٱلسَّٰٓئِحُونَ ٱلرَّٰكِعُونَ ٱلسَّٰجِدُونَ ٱلْءَامِرُونَ بِٱلْمَعْرُوفِ وَٱلنَّاهُونَ عَنِ ٱلْمُنكَرِ وَٱلْحَٰفِظُونَ لِحُدُودِ ٱللَّهِ ۗ وَبَشِّرِ ٱلْمُؤْمِنِينَ", "(Mereka itu ialah): orang-orang yang bertaubat, yang beribadat, yang memuji Allah, yang mengembara (untuk menuntut ilmu dan mengembangkan Islam), yang rukuk, yang sujud, yang menyuruh berbuat kebaikan dan yang melarang daripada kejahatan, serta yang menjaga batas-batas hukum Allah. Dan gembirakanlah orang-orang yang beriman (yang bersifat demikian).", R.raw.taubah112));
        arrayList.add(new VerseActivity("Taubah", "مَا كَانَ لِلنَّبِىِّ وَٱلَّذِينَ ءَامَنُوٓا۟ أَن يَسْتَغْفِرُوا۟ لِلْمُشْرِكِينَ وَلَوْ كَانُوٓا۟ أُو۟لِى قُرْبَىٰ مِنۢ بَعْدِ مَا تَبَيَّنَ لَهُمْ أَنَّهُمْ أَصْحَٰبُ ٱلْجَحِيمِ", "Tidaklah dibenarkan bagi Nabi dan orang-orang yang beriman, meminta ampun bagi orang-orang musyrik, sekalipun orang itu kaum kerabat sendiri, sesudah nyata bagi mereka bahawa orang-orang musyrik itu adalah ahli neraka.", R.raw.taubah113));
        arrayList.add(new VerseActivity("Taubah", "وَمَا كَانَ ٱسْتِغْفَارُ إِبْرَٰهِيمَ لِأَبِيهِ إِلَّا عَن مَّوْعِدَةٍ وَعَدَهَآ إِيَّاهُ فَلَمَّا تَبَيَّنَ لَهُۥٓ أَنَّهُۥ عَدُوٌّ لِّلَّهِ تَبَرَّأَ مِنْهُ ۚ إِنَّ إِبْرَٰهِيمَ لَأَوَّٰهٌ حَلِيمٌ", "Dan bukanlah istighfar Nabi Ibrahim bagi bapanya (dibuat) melainkan kerana adanya janji yang dijanjikan kepadanya; dan apabila ternyata kepada Nabi Ibrahim bahawa bapanya musuh bagi Allah, ia pun berlepas diri daripadanya. Sesungguhnya Nabi Ibrahim itu lembut hati lagi penyabar.", R.raw.taubah114));
        arrayList.add(new VerseActivity("Taubah", "﻿وَمَا كَانَ ٱللَّهُ لِيُضِلَّ قَوْمًۢا بَعْدَ إِذْ هَدَىٰهُمْ حَتَّىٰ يُبَيِّنَ لَهُم مَّا يَتَّقُونَ ۚ إِنَّ ٱللَّهَ بِكُلِّ شَىْءٍ عَلِيمٌ", "Dan Allah tidak sekali-kali menjadikan sesuatu kaum itu sesat sesudah Ia memberi hidayah petunjuk kepada mereka, sebelum Ia menerangkan kepada mereka apa yang mereka wajib memelihara dan melindungi diri daripadanya; sesungguhnya Allah Maha Mengetahui akan tiap-tiap sesuatu.", R.raw.taubah115));
        arrayList.add(new VerseActivity("Taubah", "إِنَّ ٱللَّهَ لَهُۥ مُلْكُ ٱلسَّمَٰوَٰتِ وَٱلْأَرْضِ ۖ يُحْىِۦ وَيُمِيتُ ۚ وَمَا لَكُم مِّن دُونِ ٱللَّهِ مِن وَلِىٍّ وَلَا نَصِيرٍ", "Sesungguhnya Allah jualah yang menguasai segala alam langit dan bumi; Ia menghidupkan dan mematikan; dan tidaklah ada bagi kamu selain dari Allah sesiapa pun yang menjadi pelindung dan juga yang menjadi penolong.", R.raw.taubah116));
        arrayList.add(new VerseActivity("Taubah", "﻿لَّقَد تَّابَ ٱللَّهُ عَلَى ٱلنَّبِىِّ وَٱلْمُهَٰجِرِينَ وَٱلْأَنصَارِ ٱلَّذِينَ ٱتَّبَعُوهُ فِى سَاعَةِ ٱلْعُسْرَةِ مِنۢ بَعْدِ مَا كَادَ يَزِيغُ قُلُوبُ فَرِيقٍ مِّنْهُمْ ثُمَّ تَابَ عَلَيْهِمْ ۚ إِنَّهُۥ بِهِمْ رَءُوفٌ رَّحِيمٌ", "Sesungguhnya Allah telah menerima taubat Nabi dan orang-orang Muhajirin dan Ansar yang mengikutnya (berjuang) dalam masa kesukaran, sesudah hampir-hampir terpesong hati segolongan dari mereka (daripada menurut Nabi untuk berjuang); kemudian Allah menerima taubat mereka; sesungguhnya Allah Amat belas, lagi Maha Mengasihani terhadap mereka.", R.raw.taubah117));
        arrayList.add(new VerseActivity("Taubah", "﻿وَعَلَى ٱلثَّلَٰثَةِ ٱلَّذِينَ خُلِّفُوا۟ حَتَّىٰٓ إِذَا ضَاقَتْ عَلَيْهِمُ ٱلْأَرْضُ بِمَا رَحُبَتْ وَضَاقَتْ عَلَيْهِمْ أَنفُسُهُمْ وَظَنُّوٓا۟ أَن لَّا مَلْجَأَ مِنَ ٱللَّهِ إِلَّآ إِلَيْهِ ثُمَّ تَابَ عَلَيْهِمْ لِيَتُوبُوٓا۟ ۚ إِنَّ ٱللَّهَ هُوَ ٱلتَّوَّابُ ٱلرَّحِيمُ", "Dan (Allah menerima pula taubat) tiga orang yang ditangguhkan (penerimaan taubat mereka) hingga apabila bumi yang luas ini (terasa) sempit kepada mereka (kerana mereka dipulaukan), dan hati mereka pula menjadi sempit (kerana menanggung dukacita), serta mereka yakin bahawa tidak ada tempat untuk mereka lari dari (kemurkaan) Allah melainkan (kembali bertaubat) kepadaNya; kemudian Allah (memberi taufiq serta) menerima taubat mereka supaya mereka kekal bertaubat. Sesungguhnya Allah Dia lah Penerima taubat lagi Maha Mengasihani.", R.raw.taubah118));
        arrayList.add(new VerseActivity("Taubah", "يَٰٓأَيُّهَا ٱلَّذِينَ ءَامَنُوا۟ ٱتَّقُوا۟ ٱللَّهَ وَكُونُوا۟ مَعَ ٱلصَّٰدِقِينَ", "Wahai orang-orang yang beriman! Bertaqwalah kamu kepada Allah, dan hendaklah kamu berada bersama-sama orang-orang yang benar.", R.raw.taubah119));
        arrayList.add(new VerseActivity("Taubah", "مَا كَانَ لِأَهْلِ ٱلْمَدِينَةِ وَمَنْ حَوْلَهُم مِّنَ ٱلْأَعْرَابِ أَن يَتَخَلَّفُوا۟ عَن رَّسُولِ ٱللَّهِ وَلَا يَرْغَبُوا۟ بِأَنفُسِهِمْ عَن نَّفْسِهِۦ ۚ ذَٰلِكَ بِأَنَّهُمْ لَا يُصِيبُهُمْ ظَمَأٌ وَلَا نَصَبٌ وَلَا مَخْمَصَةٌ فِى سَبِيلِ ٱللَّهِ وَلَا يَطَـُٔونَ مَوْطِئًا يَغِيظُ ٱلْكُفَّارَ وَلَا يَنَالُونَ مِنْ عَدُوٍّ نَّيْلًا إِلَّا كُتِبَ لَهُم بِهِۦ عَمَلٌ صَٰلِحٌ ۚ إِنَّ ٱللَّهَ لَا يُضِيعُ أَجْرَ ٱلْمُحْسِنِينَ", "Tidaklah patut bagi penduduk Madinah dan orang-orang yang di sekeliling mereka dari orang-orang \"A'raab\" ketinggalan daripada (turut berperang bersama) Rasulullah; dan tidaklah patut mereka mengasihi diri mereka sendiri dengan tidak menghiraukan Rasulullah. Yang demikian kerana sesungguhnya (tiap-tiap kali) mereka merasai dahaga, dan merasai penat lelah, dan juga merasai lapar (dalam perjuangan) pada jalan Allah; dan (tiap-tiap kali) mereka menjejak sesuatu tempat yang menimbulkan kemarahan orang-orang kafir; dan juga (tiap-tiap kali) mereka menderita sesuatu yang mencederakan dari pihak musuh - melainkan semuanya itu ditulis bagi mereka: (pahala) amal yang soleh. Sesungguhnya Allah tidak menghilangkan pahala orang-orang yang berusaha memperbaiki amalannya.", R.raw.taubah120));

        /*ayat 121-129*/
        arrayList.add(new VerseActivity("Taubah", "وَلَا يُنفِقُونَ نَفَقَةً صَغِيرَةً وَلَا كَبِيرَةً وَلَا يَقْطَعُونَ وَادِيًا إِلَّا كُتِبَ لَهُمْ لِيَجْزِيَهُمُ ٱللَّهُ أَحْسَنَ مَا كَانُوا۟ يَعْمَلُونَ", "Dan tidak pula mereka membelanjakan sesuatu perbelanjaan yang kecil, atau yang besar; dan tidak mereka melintas sesuatu lembah, melainkan ditulis pahala bagi mereka, supaya Allah membalas dengan balasan yang lebih baik dari apa yang mereka telah kerjakan.", R.raw.taubah121));
        arrayList.add(new VerseActivity("Taubah", "۞ وَمَا كَانَ ٱلْمُؤْمِنُونَ لِيَنفِرُوا۟ كَآفَّةً ۚ فَلَوْلَا نَفَرَ مِن كُلِّ فِرْقَةٍ مِّنْهُمْ طَآئِفَةٌ لِّيَتَفَقَّهُوا۟ فِى ٱلدِّينِ وَلِيُنذِرُوا۟ قَوْمَهُمْ إِذَا رَجَعُوٓا۟ إِلَيْهِمْ لَعَلَّهُمْ يَحْذَرُونَ", "Dan tidaklah (betul dan elok) orang-orang yang beriman keluar semuanya (pergi berperang); oleh itu, hendaklah keluar sebahagian sahaja dari tiap-tiap puak di antara mereka, supaya orang-orang (yang tinggal) itu mempelajari secara mendalam ilmu yang dituntut di dalam agama, dan supaya mereka dapat mengajar kaumnya (yang keluar berjuang) apabila orang-orang itu kembali kepada mereka; mudah-mudahan mereka dapat berjaga-jaga (dari melakukan larangan Allah).", R.raw.taubah122));
        arrayList.add(new VerseActivity("Taubah", "يَٰٓأَيُّهَا ٱلَّذِينَ ءَامَنُوا۟ قَٰتِلُوا۟ ٱلَّذِينَ يَلُونَكُم مِّنَ ٱلْكُفَّارِ وَلْيَجِدُوا۟ فِيكُمْ غِلْظَةً ۚ وَٱعْلَمُوٓا۟ أَنَّ ٱللَّهَ مَعَ ٱلْمُتَّقِينَ", "Wahai orang-orang yang beriman! Perangilah orang-orang kafir musyrik yang berdekatan dengan kamu; dan biarlah mereka merasai sikap kekerasan (serta ketabahan hati) yang ada pada kamu; dan ketahuilah sesungguhnya Allah beserta orang-orang yang bertaqwa (dengan memberikan pertolonganNya).", R.raw.taubah123));
        arrayList.add(new VerseActivity("Taubah", "﻿وَإِذَا مَآ أُنزِلَتْ سُورَةٌ فَمِنْهُم مَّن يَقُولُ أَيُّكُمْ زَادَتْهُ هَٰذِهِۦٓ إِيمَٰنًا ۚ فَأَمَّا ٱلَّذِينَ ءَامَنُوا۟ فَزَادَتْهُمْ إِيمَٰنًا وَهُمْ يَسْتَبْشِرُونَ", "Dan apabila diturunkan sesuatu surah (dari Al-Quran) maka di antara mereka (yang munafik) ada yang bertanya (secara mengejek): \"Siapakah di antara kamu yang imannya bertambah disebabkan oleh surah ini?\" Adapun orang-orang yang beriman, maka surah itu menambahkan iman mereka, sedang mereka bergembira (dengan turunnya).", R.raw.taubah124));
        arrayList.add(new VerseActivity("Taubah", "﻿وَأَمَّا ٱلَّذِينَ فِى قُلُوبِهِم مَّرَضٌ فَزَادَتْهُمْ رِجْسًا إِلَىٰ رِجْسِهِمْ وَمَاتُوا۟ وَهُمْ كَٰفِرُونَ", "Adapun orang-orang yang ada penyakit (kufur) dalam hati mereka maka surah Al-Quran itu menambahkan kekotoran (kufur) kepada kekotoran (kufur) yang ada pada mereka; dan mereka mati, sedang mereka berkeadaan kafir.", R.raw.taubah125));
        arrayList.add(new VerseActivity("Taubah", "أَوَلَا يَرَوْنَ أَنَّهُمْ يُفْتَنُونَ فِى كُلِّ عَامٍ مَّرَّةً أَوْ مَرَّتَيْنِ ثُمَّ لَا يَتُوبُونَ وَلَا هُمْ يَذَّكَّرُونَ", "Dan (patutkah) mereka (berdegil) tidak mahu memperhatikan, bahawa mereka dicuba (dengan berbagai-bagai bencana) pada tiap-tiap tahun, sekali atau dua kali; kemudian mereka tidak juga bertaubat, dan tidak pula mereka mahu beringat (dan insaf)?", R.raw.taubah126));
        arrayList.add(new VerseActivity("Taubah", "وَإِذَا مَآ أُنزِلَتْ سُورَةٌ نَّظَرَ بَعْضُهُمْ إِلَىٰ بَعْضٍ هَلْ يَرَىٰكُم مِّنْ أَحَدٍ ثُمَّ ٱنصَرَفُوا۟ ۚ صَرَفَ ٱللَّهُ قُلُوبَهُم بِأَنَّهُمْ قَوْمٌ لَّا يَفْقَهُونَ", "Dan apabila diturunkan satu surah dari Al-Quran (mendedahkan keburukan orang-orang munafik itu) setengah mereka memandang kepada setengahnya yang lain sambil berkata: \"Adakah sesiapa nampak kamu (kalau kita undur dari sini)?\" Kemudian mereka berpaling pergi (dengan meninggalkan majlis Nabi); Allah memalingkan hati mereka (daripada iman), disebabkan mereka kaum yang tidak (mahu) mengerti.", R.raw.taubah127));
        arrayList.add(new VerseActivity("Taubah", "﻿لَقَدْ جَآءَكُمْ رَسُولٌ مِّنْ أَنفُسِكُمْ عَزِيزٌ عَلَيْهِ مَا عَنِتُّمْ حَرِيصٌ عَلَيْكُم بِٱلْمُؤْمِنِينَ رَءُوفٌ رَّحِيمٌ", "Sesungguhnya telah datang kepada kamu seorang Rasul dari golongan kamu sendiri (iaitu Nabi Muhammad s.a.w), yang menjadi sangat berat kepadanya sebarang kesusahan yang ditanggung oleh kamu, yang sangat tamak (inginkan) kebaikan bagi kamu, (dan) ia pula menumpahkan perasaan belas serta kasih sayangnya kepada orang-orang yang beriman.", R.raw.taubah128));
        arrayList.add(new VerseActivity("Taubah", "فَإِن تَوَلَّوْا۟ فَقُلْ حَسْبِىَ ٱللَّهُ لَآ إِلَٰهَ إِلَّا هُوَ ۖ عَلَيْهِ تَوَكَّلْتُ ۖ وَهُوَ رَبُّ ٱلْعَرْشِ ٱلْعَظِيمِ", "Kemudian jika mereka berpaling ingkar, maka katakanlah (wahai Muhammad): \"cukuplah bagiku Allah (yang menolong dan memeliharaku), tiada Tuhan (yang berhak disembah) melainkan Dia; kepadaNya aku berserah diri, dan Dia lah yang mempunyai Arasy yang besar.\"", R.raw.taubah129));

        adapter = new QuranActivity(this, R.layout.verseview, arrayList);
        verseList.setAdapter(adapter);
    }

    Menu menu;

    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        getMenuInflater().inflate(R.menu.menu_main, menu);
        return true;
    }

    private MediaPlayer mp = null;

    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        switch (item.getItemId()) {
            case R.id.action_playall:
                mp = MediaPlayer.create(this, R.raw.taubahfull);
                mp.start();
                break;
            case R.id.action_stop:
                if(mp != null)
                    mp.stop();;
                break;
            case R.id.action_info:
                // User chose the "Favorite" action, mark the current item
                // as a favorite...
                break;
            case R.id.action_malay:
                if(mp != null)
                    mp.stop();
                Intent i = new Intent(SurahTaubahMalay.this, SurahTaubahEnglish.class);
                startActivity(i);
                break;
        }
        return super.onOptionsItemSelected(item);
    }
}